export interface StartupProps {
  id?: number;
  startup_name: string;
  logo: string | null;
  foundation_year: number | null;
  value_proposal_en: string;
  value_proposal_pt: string;
  last_update: string;
  vertical: string;
  business_model: string;
  country: string;
  flag: string;
}

export interface ExpertProps {
  id: number;
  name: string;
  last_name: string;
  linkedin: string;
  description_en: string | null;
  description_pt: string | null;
  languages_en: string;
  languages_pt: string;
  languages_en_array: string[];
  languages_pt_array: string[];
  work_field_en: string[];
  work_field_pt: string[];
  country_en: string;
  country_pt: string;
  photo: string | null;
  flag: string;
}

export interface TeamProps {
  id: number;
  name: string;
  linkedin: string;
  position_pt: string;
  position_en: string;
  photo: string;
}

export interface VerticalTypes {
  id: number;
  value: string;
  label_en: string;
  label_pt: string;
}

export interface CountriesList {
  id: number;
  value: string;
  label_en: string;
  label_pt: string;
}

export interface BusinessModel {
  id: number;
  value: string;
  label: string;
}

export interface OperationalStage {
  id: number;
  value: string;
  label_en: string;
  label_pt: string;
}

export interface ChallengesList {
  id: number;
  value: string;
  label_en: string;
  label_pt: string;
}

export interface TRLList {
  id: number;
  value: string;
  label_en: string;
  label_pt: string;
}

export interface ServiceProductsStartup {
  id: number;
  value: string;
  label_en: string;
  label_pt: string;
}

export interface ExpertsEbook {
  id: number;
  title_en: string;
  title_pt: string;
  link_en: string;
  link_pt: string;
  img_en: string;
  img_pt: string;
}

type InfoFlags = {
  [key: string]: string;
};

export const startupsList: StartupProps[] = [
  {
    id: 1,
    startup_name: "Vaca Roxa",
    foundation_year: 2022,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "AgriTech",
    business_model: "B2B2C",
    country: "Brasil",
    logo: "/assets/startups/logos/01_vaca_roxa.jpg",
    flag: "brazil",
  },
  {
    id: 2,
    startup_name: "Grupo Gestão Saúde",
    foundation_year: 2023,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "SaaS",
    business_model: "B2B",
    country: "Brasil",
    logo: "/assets/startups/logos/02_grupo_gestao_saude.png",
    flag: "brazil",
  },
  {
    id: 3,
    startup_name: "DS7 BANK",
    foundation_year: 2021,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "FinTech",
    business_model: "B2B2C",
    country: "Brasil",
    logo: "/assets/startups/logos/03_ds7_bank.png",
    flag: "brazil",
  },
  {
    id: 4,
    startup_name: "mub",
    foundation_year: 2020,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "SaaS",
    business_model: "B2B",
    country: "Brasil",
    logo: "/assets/startups/logos/04_mub.png",
    flag: "brazil",
  },
  {
    id: 5,
    startup_name: "Meister Safe System",
    foundation_year: 2020,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "HealthTech",
    business_model: "B2B e B2C",
    country: "Brasil",
    logo: "/assets/startups/logos/05_meister_safe.jpg",
    flag: "brazil",
  },
  {
    id: 6,
    startup_name: "Vishv Foods and beverages LLP",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2C",
    country: "India",
    logo: "/assets/startups/logos/06_vishv_foods.png",
    flag: "india",
  },
  {
    id: 7,
    startup_name: "Daksyam group",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/07_daksyam.png",
    flag: "india",
  },
  {
    id: 8,
    startup_name: "Agri Joy Pvt Ltd",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2C",
    country: "India",
    logo: "/assets/startups/logos/08_agri.png",
    flag: "india",
  },
  {
    id: 9,
    startup_name: "Energysaver Business Solutions and Technology PVT LTD",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/09_energysaver.png",
    flag: "india",
  },
  {
    id: 10,
    startup_name: "DroneArch systems And Technologies Private Limited",
    foundation_year: 2023,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "Drones",
    business_model: "B2G",
    country: "India",
    logo: "/assets/startups/logos/10_dronearch.jpeg",
    flag: "india",
  },
  {
    id: 11,
    startup_name: "Curium Life Tech",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/11_curium.png",
    flag: "india",
  },
  {
    id: 12,
    startup_name: "MACHKG ICT LLP",
    foundation_year: 2022,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "IoTtech",
    business_model: "B2C",
    country: "India",
    logo: "/assets/startups/logos/12_machkg.png",
    flag: "india",
  },
  {
    id: 13,
    startup_name: "NANO BUBBLES BANGALORE Pvt Ltd",
    foundation_year: 2017,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "CleanTech",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/13_nano_bubbles.png",
    flag: "india",
  },
  {
    id: 14,
    startup_name: "Insignia Consultancy",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2C",
    country: "India",
    logo: "/assets/startups/logos/14_insignia.png",
    flag: "india",
  },
  {
    id: 15,
    startup_name: "Maathru health products",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/15_maathru.png",
    flag: "india",
  },
  {
    id: 16,
    startup_name: "Hetrogenous Communication Technologies Pvt Ltd",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/16_hetrogenous.png",
    flag: "india",
  },
  {
    id: 17,
    startup_name: "PRESET Building Systems",
    foundation_year: 2023,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "PropeTech",
    business_model: "B2C",
    country: "India",
    logo: "/assets/startups/logos/17_preset_building.png",
    flag: "india",
  },
  {
    id: 18,
    startup_name: "INN-FORCE TECHNOLOGIES PRIVATE LIMITED",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/18_inn-force.png",
    flag: "india",
  },
  {
    id: 19,
    startup_name: "JALODBUST",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2C",
    country: "India",
    logo: "/assets/startups/logos/19_jalodbust.png",
    flag: "india",
  },
  {
    id: 20,
    startup_name: "Transfigure Technologies Pvt ltd",
    foundation_year: 2017,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "SaasTech",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/20_transfigure.png",
    flag: "india",
  },
  {
    id: 21,
    startup_name: "MetaBrix Labs",
    foundation_year: 2022,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "AI",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/21_metabrix.jpg",
    flag: "india",
  },
  {
    id: 22,
    startup_name: "GTO Pay Appz HR Solutions Private Limited",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/22_gto_pay.png",
    flag: "india",
  },
  {
    id: 23,
    startup_name: "PAKSHIMITRA POULTRY TECHNOLOGIES PRIVATE LIMITED",
    foundation_year: 2018,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "AgriTech",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/23_pakshimitra.png",
    flag: "india",
  },
  {
    id: 24,
    startup_name: "Fabrik",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/24_fabrik.png",
    flag: "india",
  },
  {
    id: 25,
    startup_name: "Clear Water Dynamics Pvt Ltd",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2G",
    country: "India",
    logo: "/assets/startups/logos/25_clear_water.png",
    flag: "india",
  },
  {
    id: 26,
    startup_name: "Life Bound Technologies Pvt Ltd",
    foundation_year: 2021,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "MedTech",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/26_life_bound.jpg",
    flag: "india",
  },
  {
    id: 27,
    startup_name: "ARFICUS PRIVATE LIMITED",
    foundation_year: 2019,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "HealthTech",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/27_arficus.jpg",
    flag: "india",
  },
  {
    id: 28,
    startup_name: "StatValu",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/28_statvalu.png",
    flag: "india",
  },
  {
    id: 29,
    startup_name: "Healthsure (M/S Kariakali Amman Foods Private Limited)",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "-",
    country: "India",
    logo: "/assets/startups/logos/29_healthsure.png",
    flag: "india",
  },
  {
    id: 30,
    startup_name: "TECSMEN INNOVATION ",
    foundation_year: 2021,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "IoTtech",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/30_tecsmen.jpeg",
    flag: "india",
  },
  {
    id: 31,
    startup_name: "Sabhyasha Retail Tech Pvt Ltd.",
    foundation_year: 2022,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "E-commerce",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/31_sabhyasha.png",
    flag: "india",
  },
  {
    id: 32,
    startup_name: "Stocktick Capital",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2C",
    country: "India",
    logo: "/assets/startups/logos/32_stocktick.png",
    flag: "india",
  },
  {
    id: 33,
    startup_name: "Offset Global Technologies Pvt Ltd",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/33_offset_global.png",
    flag: "india",
  },
  {
    id: 34,
    startup_name: "Manentia Ai",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/34_manentia.png",
    flag: "india",
  },
  {
    id: 35,
    startup_name: "Nava Design and Innovation Pvt Ltd",
    foundation_year: 2016,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "AgriTech",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/35_nava.jpg",
    flag: "india",
  },
  {
    id: 36,
    startup_name: "ATTMANS",
    foundation_year: 2023,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/36_attmans.png",
    flag: "india",
  },
  {
    id: 37,
    startup_name: "VITT AI",
    foundation_year: 2017,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "FinTech",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/37_vitt.png",
    flag: "india",
  },
  {
    id: 38,
    startup_name: "Pentavalent Bio Sciences Private Limited",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/38_pentavalent.png",
    flag: "india",
  },
  {
    id: 39,
    startup_name: "GFresh Agrotech Pvt Ltd",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/39_gfresh.png",
    flag: "india",
  },
  {
    id: 40,
    startup_name: "Vector Technics",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/40_vector.png",
    flag: "india",
  },
  {
    id: 41,
    startup_name: "CluCloud Innovations Pvt Ltd",
    foundation_year: 2022,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "FinTech",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/41_clucloud.jpg",
    flag: "india",
  },
  {
    id: 42,
    startup_name: "Veenero Sustainable Solutions",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/42_veenero.png",
    flag: "india",
  },
  {
    id: 43,
    startup_name: "Aspalli Green Sustainable Ecosystem Pvt Ltd",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2G",
    country: "India",
    logo: "/assets/startups/logos/43_aspalli.png",
    flag: "india",
  },
  {
    id: 44,
    startup_name: "Teakshed AI Pvt Ltd",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/44_teakshed.png",
    flag: "india",
  },
  {
    id: 45,
    startup_name: "Swayam Analytics Pvt Ltd",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/45_swayam.png",
    flag: "india",
  },
  {
    id: 46,
    startup_name: "CANORX Motors Private Limited",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/46_canorx.png",
    flag: "india",
  },
  {
    id: 47,
    startup_name: "Xecutables Ptv Ltd",
    foundation_year: 2020,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "HRTech",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/47_xecutables.png",
    flag: "india",
  },
  {
    id: 48,
    startup_name: "ProenX Pte. Ltd",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/48_proenx.png",
    flag: "india",
  },
  {
    id: 49,
    startup_name: "Safsu",
    foundation_year: 2023,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "CleanTech",
    business_model: "B2C",
    country: "Finland",
    logo: "/assets/startups/logos/49_safsu.jpg",
    flag: "finland",
  },
  {
    id: 50,
    startup_name: "Austhraa motors private limited",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2C",
    country: "India",
    logo: "/assets/startups/logos/50_austhraa.png",
    flag: "india",
  },
  {
    id: 51,
    startup_name: "Divine Campus Infotech Pvt Ltd",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/51_divine.png",
    flag: "india",
  },
  {
    id: 52,
    startup_name: "Dhanvantri Biomedical Private Limited",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2C",
    country: "India",
    logo: "/assets/startups/logos/52_dhanvantri.png",
    flag: "india",
  },
  {
    id: 53,
    startup_name: "TechXcl India Pvt. Ltd",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/53_techxcl.png",
    flag: "india",
  },
  {
    id: 54,
    startup_name: "Qure.ai Technologies Private limited",
    foundation_year: 2019,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "HealthTech",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/54_qure.png",
    flag: "india",
  },
  {
    id: 55,
    startup_name: "Azooka Labs Pvt Ltd",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/55_azooka.png",
    flag: "india",
  },
  {
    id: 56,
    startup_name: "Dentifrice Private Limited",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/56_dentifrice.png",
    flag: "india",
  },
  {
    id: 57,
    startup_name: "HICET SUSTAINABLE SOLUTIONS PRIVATE LIMITED",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2G",
    country: "India",
    logo: "/assets/startups/logos/57_hicet.png",
    flag: "india",
  },
  {
    id: 58,
    startup_name: "SAPTKRISHI SCIENTIFIC PRIVATE LIMITED",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/58_saptkrishi.png",
    flag: "india",
  },
  {
    id: 59,
    startup_name: "Whrrl",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/59_whrrl.png",
    flag: "india",
  },
  {
    id: 60,
    startup_name: "ORGANIC MILE PRIVATE LIMITED",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/60_organic_mile.png",
    flag: "india",
  },
  {
    id: 61,
    startup_name: "Xrathus, Inc.",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "USA",
    logo: "/assets/startups/logos/61_xrathus.png",
    flag: "usa",
  },
  {
    id: 62,
    startup_name: "Neidhal Cadet Service",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/62_neidhal.png",
    flag: "india",
  },
  {
    id: 63,
    startup_name: "Uravu Labs Private Limited",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "-",
    country: "India",
    logo: "/assets/startups/logos/63_uravu.png",
    flag: "india",
  },
  {
    id: 64,
    startup_name: "E-Veritas Energia",
    foundation_year: 2023,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "EdTech",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/64_everitas.png",
    flag: "india",
  },
  {
    id: 65,
    startup_name: "Empresasecia",
    foundation_year: 2019,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "E-healfth",
    business_model: "B2C",
    country: "Brasil",
    logo: "/assets/startups/logos/65_empresasecia.jpg",
    flag: "brazil",
  },
  {
    id: 66,
    startup_name: "SagaPro Edtech Ltda",
    foundation_year: 2021,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "EdTech",
    business_model: "B2B",
    country: "Brasil",
    logo: "/assets/startups/logos/66_sagapro.png",
    flag: "brazil",
  },
  {
    id: 67,
    startup_name: "Meu Cuidador - Marketplace de Soluções em Saúde",
    foundation_year: 2020,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "21/01/2024",
    vertical: "HealthTech",
    business_model: "B2B2C",
    country: "Brasil",
    logo: "/assets/startups/logos/67_meu_cuidador.jpeg",
    flag: "brazil",
  },
  {
    id: 68,
    startup_name: "Sabhyasha Retail Tech Pvt. Ltd.",
    foundation_year: 2022,
    value_proposal_en:
      "Linking Artisans & Markets; Diverse Crafts, Empowerment, AI-Enhanced",
    value_proposal_pt:
      "Conectando Artesãos e Mercados; Artes Diversas, Empoderamento, Aprimorado por IA",
    last_update: "05/02/2024",
    vertical: "RetailTech - Tecnologia de Varejo",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/68_babhyasha.jpg",
    flag: "india",
  },
  {
    id: 69,
    startup_name: "Meister Safe System",
    foundation_year: 2020,
    value_proposal_en: "We take care of the air you breathe",
    value_proposal_pt: "Cuidamos do ar que você respira",
    last_update: "05/02/2024",
    vertical: "Healthtech - Tecnologia de Saúde",
    business_model: "B2B",
    country: "Brasil",
    logo: "/assets/startups/logos/69_meister_safe.jpg",
    flag: "brazil",
  },
  {
    id: 70,
    startup_name: "mub - Sistema de Gestão de Workflows",
    foundation_year: 2020,
    value_proposal_en:
      "Total control, simplified management, operational efficiency",
    value_proposal_pt:
      "Controle total, gestão simplificada, eficiência operacional",
    last_update: "05/02/2024",
    vertical: "SaaS - Software como Serviço",
    business_model: "B2B",
    country: "Brasil",
    logo: "/assets/startups/logos/70_mub.png",
    flag: "brazil",
  },
  {
    id: 71,
    startup_name: "AQUi9",
    foundation_year: 2022,
    value_proposal_en:
      "Increase productivity, profitability, and operational efficiency",
    value_proposal_pt:
      "Aumentar a produtividade, lucratividade e a eficiência operacional",
    last_update: "05/02/2024",
    vertical: "AgTech - Tecnologia Agrícola",
    business_model: "B2B",
    country: "Brasil",
    logo: "/assets/startups/logos/71_aqui9.png",
    flag: "brazil",
  },
  {
    id: 72,
    startup_name: "PRESET BUILDING SYSTEMS PVT LTD",
    foundation_year: 2023,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "05/02/2024",
    vertical: "PropeTech - real estate technology",
    business_model: "B2C",
    country: "India",
    logo: "/assets/startups/logos/72_hamsa.png",
    flag: "india",
  },
  {
    id: 73,
    startup_name: "Avas DigiTech",
    foundation_year: 2020,
    value_proposal_en: "Smaarket: Empowering Investors, Elevating Startups",
    value_proposal_pt: "Smaarket: Empoderando Investidores, Elevando Startups",
    last_update: "05/02/2024",
    vertical: "FinTech-financial technologies",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/73_avas_digitech.jpg",
    flag: "india",
  },
];

export const infoFlags: InfoFlags = {
  brazil: "/assets/flags/brazil.svg",
  colombia: "/assets/flags/colombia.svg",
  finland: "/assets/flags/finland.svg",
  india: "/assets/flags/india.svg",
  usa: "/assets/flags/usa.svg",
};

export const expertsList: ExpertProps[] = [
  {
    id: 1,
    name: "Yadira",
    last_name: "Galeano",
    linkedin: "https://www.linkedin.com/in/yadirdiazgaleano/",
    description_en:
      "I started my career as a business consultant, working on projects ranging from established companies to emerging ventures. Over the years, I have gained valuable skills in areas such as business strategy, financial analysis, process optimization, and team development. My passion for startups stems from the realization that they are true engines of innovation and disruption. The agility, creativity, and entrepreneurial mindset present in this environment have captivated me. Over time, I realized I wanted to direct my expertise to support visionary entrepreneurs in realizing their bold ideas.",
    description_pt:
      "Iniciei minha carreira como consultor de negócios, trabalhando em projetos que abrangem desde empresas estabelecidas até empreendimentos emergentes. Ao longo dos anos, adquiri habilidades valiosas em áreas como estratégia de negócios, análise financeira, otimização de processos e desenvolvimento de equipes. Minha paixão por startups surgiu da percepção de que são verdadeiros motores de inovação e disrupção. A agilidade, a criatividade e a mentalidade empreendedora presentes nesse ambiente me cativaram. Ao longo do tempo, percebi que queria direcionar minha expertise para apoiar empreendedores visionários na realização de suas ideias ousadas",
    languages_en: "pt - sp",
    languages_pt: "pt - es",
    languages_en_array: ["Portuguese", "Spanish"],
    languages_pt_array: ["Português", "Espanhol"],
    work_field_en: [
      "Partnerships",
      "Internationalization",
      "Leadership",
      "Negotiation",
      "Strategic Vision",
      "Management",
    ],
    work_field_pt: [
      "Parcerias",
      "Internacionalização",
      "Liderança",
      "Negociação",
      "Visão estratégica",
      "Gestão",
    ],
    country_en: "Colombia",
    country_pt: "Colômbia",
    photo: "/assets/experts/01_yadira_galeano.png",
    flag: "colombia",
  },
  {
    id: 2,
    name: "Claudio",
    last_name: "de Souza",
    linkedin:
      "https://www.linkedin.com/in/claudio-alexandre-de-souza-cas-48709125/",
    description_en:
      "I have been working as a consultant for over 10 years for companies in the tourism, hospitality, and other sectors, as can be seen on the Xenios Institute website (www.xenios.org.br). I have been involved in mentoring for over 10 years in projects such as hackathons, NASA Space App, and as an innovation advisor for the hotel management startup Macna Digital Hotels.",
    description_pt:
      "Atua com consultoria há mais de 10 anos para empresas de turismo, hotelaria e outras que podem ser observada no site do Instituto Xenios (www.xenios.org.br). Atuo há mais de 10 anos com mentorias em projetos como hackathons, NASA Space App e como conselheiro para Inovação da startup de administração hoteleira Macna Digital Hotels.",
    languages_en: "pt - sp",
    languages_pt: "pt - es",
    languages_en_array: ["Portuguese", "Spanish"],
    languages_pt_array: ["Português", "Espanhol"],
    work_field_pt: ["Parcerias", "Liderança", "Operações"],
    work_field_en: ["Partnerships", "Leadership", "Operations"],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/02_claudio_alexandre_souza.jpeg",
    flag: "brazil",
  },
  {
    id: 3,
    name: "Felipe",
    last_name: "Seabra",
    linkedin: "Www.linkedin.com/in/felipedemouraseabra",
    description_en: "Internationalization and new business.",
    description_pt: "Internacionalização e novos negocios.",
    languages_en: "en - pt - sp",
    languages_pt: "in - pt - es",
    languages_en_array: ["English", "Portuguese", "Spanish"],
    languages_pt_array: ["Inglês", "Português", "Espanhol"],
    work_field_en: [
      "Purchasing",
      "Partnerships",
      "Internationalization",
      "Government Relations",
      "B2B Sales",
    ],
    work_field_pt: [
      "Compras",
      "Parcerias",
      "Internacionalização",
      "Governos",
      "Vendas B2B",
    ],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/03_felipe_seabra.png",
    flag: "brazil",
  },
  {
    id: 4,
    name: "Samuel",
    last_name: "Magalhães",
    linkedin:
      "https://www.linkedin.com/in/samuel-magalh%C3%A3esc?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    description_en: null,
    description_pt: null,
    languages_en: "pt - en",
    languages_pt: "pt - in",
    languages_en_array: ["Portuguese", "English"],
    languages_pt_array: ["Português", "Inglês"],
    work_field_en: [
      "Financing",
      "Business Model",
      "Investors",
      "Operations",
      "Strategic Vision",
    ],
    work_field_pt: [
      "Financiamentos",
      "Modelo de negócios",
      "Investidores",
      "Operações",
      "Visão estratégica",
    ],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/04_samuel_magalhaes.jpg",
    flag: "brazil",
  },
  {
    id: 5,
    name: "Eduardo",
    last_name: "Balardim",
    linkedin: "https://www.linkedin.com/in/eduardobalardim",
    description_en:
      "I have over 17 years of experience in the Retail and Service sectors. I am part of the Retail vertical at Anjos do Brasil, where I work as a mentor and also as an angel investor. I am also a mentor for Inovativa Brasil, which is the largest startup acceleration program in Latin America.",
    description_pt:
      "Tenho mais de 17 anos atuando nas áreas de Varejo e Serviço. Participo da vertical de Varejo da Anjos do Brasil, onde atuo como mentor e também como investidor anjo. Além disso, sou mentor na Inovativa Brasil, que é o maior programa de aceleração de startups da América Latina.",
    languages_en: "pt - sp",
    languages_pt: "pt - es",
    languages_en_array: ["Portuguese", "Spanish"],
    languages_pt_array: ["Português", "Espanhol"],
    work_field_en: [
      "Retail",
      "Mentorship",
      "Investor",
      "E-commerce",
      "Strategic Planning",
    ],
    work_field_pt: [
      "Varejo",
      "Mentoria",
      "Investidor",
      "E-commerce",
      "Planejamento Estratégico",
    ],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/05_eduardo_balardim.jpg",
    flag: "brazil",
  },
  {
    id: 6,
    name: "Guilherme",
    last_name: "Yata",
    linkedin: "http://linkedin.com/in/guilhermeyata",
    description_en:
      "I have extensive experience in the retail, engineering, and international business sectors with almost 30 years in this field. I am a member of the administrative boards of some startups here in Brazil. Additionally, I am a managing partner at S3 projects, where we develop energy transition projects for companies.",
    description_pt:
      "Tenho muita experiência na área de varejo, engenharia e negócios internacionais com quase 30 anos nessa área. Faço parte do conselho administrativos de algumas startups aqui no Brasil. Além disso sou sócio-diretor da S3 projects onde desenvolvemos projetos transição energética para empresas.",
    languages_en: "en - pt - sp",
    languages_pt: "in - pt - es",
    languages_en_array: ["English", "Portuguese", "Spanish"],
    languages_pt_array: ["Inglês", "Português", "Espanhol"],
    work_field_en: [
      "Purchasing",
      "Business Model",
      "Product",
      "Operations",
      "Strategic Vision",
    ],
    work_field_pt: [
      "Compras",
      "Modelo de negócios",
      "Produto",
      "Operações",
      "Visão estratégica",
    ],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/06_guilherme_yata.jpeg",
    flag: "brazil",
  },
  {
    id: 7,
    name: "Simone",
    last_name: "Alves",
    linkedin:
      "https://www.linkedin.com/in/simonealvesrj?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    description_en:
      "As a consultant, I have experience in market research. With startups, I have been active since 2020 as a mentor and evaluator for various acceleration programs such as Inovativa Brasil, Inovativa de Impacto, Startup Conecta, Ela Empodera, Nexus Hub, CPS Inova, among others. I am also part of the Advisory Board of the startup Polimex Bioplásticos since 2021.",
    description_pt:
      "Como consultora tenho experiência em estudos de mercado. Com startups tenho atuado desde 2020 como mentora e avaliadora de diversos programas de aceleração como Inovativa Brasil, Inovativa de Impacto, Startup Conecta, Ela Empodera, Nexus Hub, CPS Inova, entre outros. Também sou do Conselho Consultivo ds startup Polimex Bioplásticos desde 2021",
    languages_en: "pt - en",
    languages_pt: "pt - in",
    languages_en_array: ["Portuguese", "English"],
    languages_pt_array: ["Português", "Inglês"],
    work_field_en: [
      "Public Funding",
      "Business Model",
      "Product",
      "Marketing",
      "B2B Sales",
    ],
    work_field_pt: [
      "Financiamento público",
      "Modelo de negócios",
      "Produto",
      "Marketing",
      "Vendas B2B",
    ],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/07_simone_alves.jpg",
    flag: "brazil",
  },
  {
    id: 8,
    name: "Rodrigo",
    last_name: "Grossi",
    linkedin: "https://www.linkedin.com/in/rodrigogrossi/",
    description_en:
      "I am Rodrigo, Founder of STARTUPS GLOBAL LINK, partner and Chief Technology Officer at 2mi Group, Startup Manager in the International Startup Program at IFIA, Advisor to two Startups, and Official Mentor of Inovativa Brasil. I founded TeamHub and bring valuable experience from ideation to exit. I was CTO at SOLIDES, and I also have experience in renowned corporations such as TOTVS and FCA.",
    description_pt:
      "Eu sou Rodrigo, sou Founder da STARTUPS GLOBAL LINK, sócio e Diretor Executivo de Tecnologia no grupo 2mi, Startup Manager no programa Internacional de Startups da IFIA, Advisor em duas Startups e Mentor Oficial do Inovativa Brasil. Fundei a TeamHub, e trago comigo a valiosa vivência desde a ideação até o exit. Fui CTO na SOLIDES, além de ter experiência em renomadas corporações como TOTVS e FCA.",
    languages_en: "pt - en",
    languages_pt: "pt - in",
    languages_en_array: ["Portuguese", "English"],
    languages_pt_array: ["Português", "Inglês"],
    work_field_en: [
      "Investors",
      "Business Model",
      "Leadership",
      "Pricing",
      "Valuation",
    ],
    work_field_pt: [
      "Investidores",
      "Modelo de negócios",
      "Liderança",
      "Precificação",
      "Valuation",
    ],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/08_rodrigo_grossi.jpeg",
    flag: "brazil",
  },
  {
    id: 9,
    name: "Marcos Tito",
    last_name: "Marques",
    linkedin: "https://www.linkedin.com/in/mrctito",
    description_en:
      "I am an Artificial Intelligence enthusiast with over 25 years of experience in the technology world, and my passion continues to grow. I am the kind of person who sees challenges as opportunities and learns by doing. My curiosity led me to develop an innovative AI product, and this self-instructive adventure has provided me with a wealth of practical knowledge in AI, as well as a profound understanding of its applications in the business world. Over the years, I have had the privilege of working with some of the largest software companies in the Brazilian and international markets, giving me a broad and diversified perspective of the industry. Leading multidisciplinary teams, including 100% remote teams, I have discovered the art of managing productivity and engagement from a distance. I firmly believe in the power of collaboration and communication to overcome obstacles and achieve ambitious goals. My experience spans various areas such as Education, Healthcare, Construction, HR, Hospitality, and more. I embrace both agile and traditional methodologies, and this flexibility allows me to adapt to different contexts and needs. In roles overseeing areas like Innovation, Support, Implementation, and Technology, I have developed a holistic vision that is crucial in software development.",
    description_pt:
      "Sou um entusiasta da Inteligência Artificial com mais de 25 anos de jornada no mundo da tecnologia, e minha paixão não para de crescer. Sou aquele tipo de pessoa que encara desafios como oportunidades e que aprende fazendo. Minha curiosidade me levou a desenvolver um produto de IA inovador, e essa aventura autoinstrutiva me trouxe um arsenal de conhecimentos práticos em IA, bem como uma compreensão profunda de suas aplicações no mundo dos negócios. Através dos anos, tive o privilégio de trabalhar com algumas das maiores empresas de software do mercado brasileiro e internacional, o que me proporcionou uma visão ampla e diversificada da indústria. Na liderança de equipes multidisciplinares, inclusive times 100% remotos, descobri a arte de gerenciar produtividade e engajamento à distância. Acredito firmemente no poder da colaboração e da comunicação para superar obstáculos e alcançar metas ambiciosas. Minha experiência se estende por áreas variadas como Educação, Saúde, Construção, RH, Hotelaria e muito mais. Sou adepto das metodologias ágeis e tradicionais, e essa flexibilidade me permite adaptar-me a diferentes contextos e necessidades. No comando de áreas como Inovação, Suporte, Implantação e Tecnologia, desenvolvi uma visão holística que é crucial no desenvolvimento de software.",
    languages_en: "pt",
    languages_pt: "pt",
    languages_en_array: ["Portuguese"],
    languages_pt_array: ["Português"],
    work_field_en: [
      "Partnerships",
      "Business Model",
      "Product",
      "Leadership",
      "B2B Sales",
      "Strategic Vision",
      "Company Direction",
    ],
    work_field_pt: [
      "Parcerias",
      "Modelo de negócios",
      "Produto",
      "Liderança",
      "Vendas B2B",
      "Visão estratégica",
      "Direcionamento da empresa",
    ],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/09_marcos_tito.jpeg",
    flag: "brazil",
  },
  {
    id: 10,
    name: "Andre",
    last_name: "Bretas",
    linkedin: "https://www.linkedin.com/in/andrebretas",
    description_en:
      "I work as a partner in startups and have previously served as CTO and COO in others I've been involved with. Additionally, I have experience in large corporations.",
    description_pt:
      "Atuo como sócio em startups e já atuei com CTO e COO em outras que passei. Além disso já tive experiência em grandes corporações.",
    languages_en: "pt - en",
    languages_pt: "pt - in",
    languages_en_array: ["Portuguese", "English"],
    languages_pt_array: ["Português", "Inglês"],
    work_field_en: [
      "Business Model",
      "Product",
      "E-commerce",
      "Leadership",
      "Digital Marketing",
    ],
    work_field_pt: [
      "Modelo de negócios",
      "Produto",
      "E-commerce",
      "Liderança",
      "Marketing digital",
    ],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/10_andre_bretas.jpeg",
    flag: "brazil",
  },
  {
    id: 11,
    name: "Praveen",
    last_name: "Desai",
    linkedin: "",
    description_en:
      "Engaged with startups since 2015, also fo ounded a company in 2017. Well connected with startup ecosystem in India.Established incubators in institutions of repute. Leveraging innovation and entrepreneurial ecosystem in the region.",
    description_pt:
      "Envolvido com startups desde 2015, também fundou uma empresa em 2017. Bem conectado com o ecossistema de startups na Índia. Estabeleceu incubadoras em instituições de renome. Alavancando a inovação e o ecossistema empreendedor na região.",
    languages_en: "en",
    languages_pt: "in",
    languages_en_array: ["English"],
    languages_pt_array: ["Inglês"],
    work_field_en: ["Business models"],
    work_field_pt: ["Modelo de negócios"],
    country_en: "India",
    country_pt: "Índia",
    photo: "/assets/experts/11_praveen_desai.png",
    flag: "india",
  },
  {
    id: 12,
    name: "Dr. Pranav Shimpi",
    last_name: "",
    linkedin: "",
    description_en:
      "I have been consulting organizations in health and productivity management for a decade, an insider to the startup scenario with experience to work on my own startup. I love coaching startup founders to find their purpose and start from there. I use my inquisitiveness to help shape up the journey and leverage my connection to foster quick focused growth.",
    description_pt:
      "Atuo como consultor de organizações na gestão da saúde e produtividade há uma década, um conhecedor do cenário de startups com experiência em trabalhar em minha própria startup. Adoro orientar fundadores de startups a encontrar seu propósito e começar por aí. Uso minha curiosidade para ajudar a moldar a jornada e alavancar minhas conexões para promover um crescimento rápido e focado.",
    languages_en: "en",
    languages_pt: "in",
    languages_en_array: ["English"],
    languages_pt_array: ["Inglês"],
    work_field_en: ["Risk management"],
    work_field_pt: ["Gestão de riscos"],
    country_en: "India",
    country_pt: "Índia",
    photo: "/assets/experts/12_pranav_shimpi.png",
    flag: "india",
  },
  {
    id: 13,
    name: "Dr. Shivaramakrishnan",
    last_name: "",
    linkedin: "",
    description_en: "Mentor",
    description_pt: "Mentor",
    languages_en: "en",
    languages_pt: "in",
    languages_en_array: ["English"],
    languages_pt_array: ["Inglês"],
    work_field_en: ["Private financing"],
    work_field_pt: ["Financiamento privado"],
    country_en: "India",
    country_pt: "Índia",
    photo: "/assets/experts/13_shivaramakrishnan.png",
    flag: "india",
  },
  {
    id: 14,
    name: "Wg Cdr Ragashree D Nair",
    last_name: "",
    linkedin: "",
    description_en: "Mentor & Strategic Advisor",
    description_pt: "Mentor e Consultor Estratégico",
    languages_en: "en",
    languages_pt: "in",
    languages_en_array: ["English"],
    languages_pt_array: ["Inglês"],
    work_field_en: ["Team Leadership"],
    work_field_pt: ["Liderança de equipe"],
    country_en: "India",
    country_pt: "Índia",
    photo: "/assets/experts/14_ragashree.png",
    flag: "india",
  },
  {
    id: 15,
    name: "G R Manjunath",
    last_name: "",
    linkedin: "",
    description_en:
      "Born into a business family of south india-based in bangalore-entrepreneurship is in the genes.",
    description_pt:
      "Nascido em uma família de negócios do sul da índia, baseado em bangalore, empreendedorismo está nos genes.",
    languages_en: "en",
    languages_pt: "in",
    languages_en_array: ["English"],
    languages_pt_array: ["Inglês"],
    work_field_en: ["Product-market fit"],
    work_field_pt: ["Adequação produto-mercado"],
    country_en: "India",
    country_pt: "Índia",
    photo: "/assets/experts/15_manjunath.png",
    flag: "india",
  },
  {
    id: 16,
    name: "Gedam",
    last_name: "Uday Kumar",
    linkedin: "",
    description_en:
      "Worked on real-time projects and participated in national-level competitions and hackathons",
    description_pt:
      "Trabalhei em projetos em tempo real e participei de competições e hackathons em nível nacional",
    languages_en: "en",
    languages_pt: "in",
    languages_en_array: ["English"],
    languages_pt_array: ["Inglês"],
    work_field_en: ["Product development"],
    work_field_pt: ["Desenvolvimento de produtos"],
    country_en: "India",
    country_pt: "Índia",
    photo: "/assets/experts/16_gedam.png",
    flag: "india",
  },
  {
    id: 17,
    name: "Shivam",
    last_name: "Gupta",
    linkedin: "",
    description_en: "",
    description_pt: "",
    languages_en: "en",
    languages_pt: "in",
    languages_en_array: ["English"],
    languages_pt_array: ["Inglês"],
    work_field_en: ["B2G Sales"],
    work_field_pt: ["Vendas B2G"],
    country_en: "India",
    country_pt: "Índia",
    photo: "/assets/experts/17_shivam.png",
    flag: "india",
  },
  {
    id: 18,
    name: "Karan Mehta",
    last_name: "",
    linkedin: "",
    description_en:
      "I have spent 3 years in manufacturing high precision, class 3 medical device as well as 2 years in New York working with Deloitte on Strategy and Operations for global Pharma and medtech clients...",
    description_pt:
      "Passei 3 anos na fabricação de dispositivos médicos de alta precisão, classe 3, e 2 anos em Nova York trabalhando com a Deloitte em Estratégia e Operações para clientes globais de farmácia e medtech...",
    languages_en: "en",
    languages_pt: "in",
    languages_en_array: ["English"],
    languages_pt_array: ["Inglês"],
    work_field_en: ["Product development"],
    work_field_pt: ["Desenvolvimento de produtos"],
    country_en: "India",
    country_pt: "Índia",
    photo: "/assets/experts/18_karan.png",
    flag: "india",
  },
  {
    id: 19,
    name: "Alem Moreira Martins Junior",
    last_name: "",
    linkedin: "https://www.linkedin.com/in/alemjunior",
    description_en:
      "Engagement in Technological and Cultural Transformation Projects in Large and Medium-sized companies across various industries: Pulp and Paper, Mining, Logistics, Energy, Sustainability, Technology. Currently involved in a project as the Leader of Organizational Change Management.",
    description_pt:
      "Atuação em Projetos de Transformação Tecnológica e Cultural em empresas de Grande e Médio porte em diversas linhas de negócios: Papel e Celulose, Mineração, Logística, Energia, Sustentabilidade, Tecnologia. Atualmente em um Projeto na Função de Líder de Gestão de Mudanças Organizacionais.",
    languages_en: "pt - en - sp",
    languages_pt: "pt - in - es",
    languages_en_array: ["Portuguese", "English", "Spanish"],
    languages_pt_array: ["Português", "Inglês", "Espanhol"],
    work_field_en: [
      "Networking",
      "Business Model",
      "Product",
      "Internationalization",
      "Leadership",
    ],
    work_field_pt: [
      "Rede de relacionamento",
      "Modelo de negócios",
      "Produto",
      "Internacionalização",
      "Liderança",
    ],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/19_alem_moreira.png",
    flag: "brazil",
  },
  {
    id: 20,
    name: "Marcelo",
    last_name: "Vivacqua",
    linkedin: "https://www.linkedin.com/in/marcelo-vivacqua-phd-b92b7620/",
    description_en:
      "I work as a business consultant for micro and small businesses for over 10 years as the CEO of my consulting company Conecta International Business Consultancy and as a mentor for programs such as Inovativa Brasil, Inovativa de Impacto, Sinergia Amazônia, and Founders Institute.",
    description_pt:
      "Atuo como consultor de negócios de micro e pequenas empresas há mais de 10 anos como CEO da minha empresa de consultoria Conecta International Business Consultancy e como Mentor de Programas como Inovativa Brasil, Inovativa de Impacto, Sinergia Amazônia e Founders Institute.",
    languages_en: "pt - en",
    languages_pt: "pt - in",
    languages_en_array: ["Portuguese", "English"],
    languages_pt_array: ["Português", "Inglês"],
    work_field_en: [
      "Private Financing",
      "Public Financing",
      "Networking",
      "Business Model",
      "Product",
    ],
    work_field_pt: [
      "Financiamento privado",
      "Financiamento público",
      "Rede de relacionamento",
      "Modelo de negócios",
      "Produto",
    ],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/20_marcelo_vivacqua.png",
    flag: "brazil",
  },
  {
    id: 21,
    name: "Mário Alex",
    last_name: "Santos",
    linkedin: "https://www.linkedin.com/in/marioalexsantos/",
    description_en:
      "More than 24 years of experience in the IT market, working in major software companies such as TOTVS, Softplan, and Betha Sistemas.",
    description_pt:
      "Mais de 24 anos de experiência no mercado de TI, atuando em grandes empresas de software como TOTVS, Softplan e Betha Sistemas.",
    languages_en: "pt",
    languages_pt: "pt",
    languages_en_array: ["Portuguese"],
    languages_pt_array: ["Português"],
    work_field_en: ["Team Leadership", "Operations", "B2B Sales"],
    work_field_pt: ["Liderança de equipes", "Operações", "Vendas B2B"],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/21_mario_alex.png",
    flag: "brazil",
  },
  {
    id: 22,
    name: "Leandro",
    last_name: "Figueiredo",
    linkedin: "https://www.linkedin.com/in/lefigueiredo/",
    description_en:
      "Associate Professor at Fundação Dom Cabral. Postdoctoral degree in Economic Development and Strategy.",
    description_pt:
      "Professor Associado da Fundação Dom Cabral. Pós Doutor em Desenvolvimento Econômico e Estratégia.",
    languages_en: "pt - en",
    languages_pt: "pt - in",
    languages_en_array: ["Portuguese", "English"],
    languages_pt_array: ["Português", "Inglês"],
    work_field_en: [
      "Private Financing",
      "Public Financing",
      "Networking",
      "Business Model",
      "Marketing",
    ],
    work_field_pt: [
      "Financiamento privado",
      "Financiamento público",
      "Rede de relacionamento",
      "Modelo de negócios",
      "Marketing",
    ],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/22_leandro_figueiredo.png",
    flag: "brazil",
  },
  {
    id: 23,
    name: "Dr.",
    last_name: "Viggardan",
    linkedin: "",
    description_en:
      "Mentor to 22 firm. Have my own start up India recognised company.",
    description_pt:
      "Mentor de 22 empresas. Tenho minha própria startup, reconhecida na Índia.",
    languages_en: "en",
    languages_pt: "in",
    languages_en_array: ["English"],
    languages_pt_array: ["Inglês"],
    work_field_en: ["Purchasing (Suppliers)"],
    work_field_pt: ["Compras (Fornecedores)"],
    country_en: "India",
    country_pt: "Índia",
    photo: "/assets/experts/23_viggardan.jpg",
    flag: "india",
  },
  {
    id: 24,
    name: "Boddupally",
    last_name: "Suhas",
    linkedin: "",
    description_en: "No description",
    description_pt: "Sem descrição",
    languages_en: "en",
    languages_pt: "in",
    languages_en_array: ["English"],
    languages_pt_array: ["Inglês"],
    work_field_en: ["Marketing"],
    work_field_pt: ["Marketing"],
    country_en: "India",
    country_pt: "Índia",
    photo: "/assets/experts/24_boddupally.jpg",
    flag: "india",
  },
  {
    id: 25,
    name: "Prudhvi",
    last_name: "Pakalapati",
    linkedin: "",
    description_en:
      "My role involves offering practical guidance in key areas like strategic planning, financial management, understanding market dynamics, and enhancing operational efficiency. I focus on helping you navigate the challenges of running a business, from managing funds and legalities to scaling up and networking. The goal is to partner with you, providing insights and advice tailored to your unique journey, ensuring your business thrives in a competitive environment.",
    description_pt:
      "Minha função envolve oferecer orientação prática em áreas-chave como planejamento estratégico, gestão financeira, compreensão da dinâmica de mercado e aprimoramento da eficiência operacional. Concentro-me em ajudar você a enfrentar os desafios de administrar um negócio, desde gerenciar fundos e questões legais até expandir e construir redes de contatos. O objetivo é ser seu parceiro, fornecendo insights e conselhos personalizados para a sua jornada única, garantindo que seu negócio prospere em um ambiente competitivo.",
    languages_en: "en",
    languages_pt: "in",
    languages_en_array: ["English"],
    languages_pt_array: ["Inglês"],
    work_field_en: ["Product development"],
    work_field_pt: ["Desenvolvimento de produtos"],
    country_en: "India",
    country_pt: "Índia",
    photo: "/assets/experts/25_prudhvi.png",
    flag: "india",
  },
  {
    id: 26,
    name: "Eduardo Cesar",
    last_name: "Dechechi",
    linkedin: "https://www.linkedin.com/in/dechechi/",
    description_en:
      "UniHub Coordinator (Innovation and Entrepreneurship Hub of Unioeste in Foz do Iguaçu).",
    description_pt:
      "Coordenador de UniHub (Hub de inovação e empreendedorismo da Unioeste em Foz do Iguaçu).",
    languages_en: "pt - en",
    languages_pt: "pt - in",
    languages_en_array: ["Portuguese", "English"],
    languages_pt_array: ["Português", "Inglês"],
    work_field_en: ["Governmental Relationship", "Strategic Vision"],
    work_field_pt: ["Relacionamento Governamental", "Visão estratégica"],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/26_eduardo_dechechi.png",
    flag: "brazil",
  },
];

export const teamList: TeamProps[] = [
  {
    id: 1,
    name: "Marcelo Vivacqua",
    linkedin: "https://www.linkedin.com/in/marcelo-vivacqua-phd-b92b7620/",
    position_pt: "CEO",
    position_en: "CEO",
    photo: "/assets/team/01_marcelo.jpeg",
  },
  {
    id: 2,
    name: "Rodrigo Grossi",
    linkedin: "https://www.linkedin.com/in/rodrigogrossi/",
    position_pt: "COO",
    position_en: "COO",
    photo: "/assets/team/02_rodrigo.jpeg",
  },
  {
    id: 3,
    name: "Andrio Corrêa",
    linkedin: "https://www.linkedin.com/in/andriocorrea/",
    position_pt: "CTO",
    position_en: "CTO",
    photo: "/assets/team/03_andrio.jpeg",
  },
  {
    id: 4,
    name: "Maria Goreti",
    linkedin: "https://www.linkedin.com/in/maria-goreti-freitas-phd-68a27738/",
    position_pt: "Advisor de Relações Internacionais",
    position_en: "International Relations Advisor",
    photo: "/assets/team/04_maria.jpeg",
  },
  {
    id: 5,
    name: "Mário Alex",
    linkedin: "https://www.linkedin.com/in/marioalexsantos/",
    position_pt: "Advisor de Gestão de Projetos e Experiência do Cliente",
    position_en: "Project Management and Customer Experience Advisor",
    photo: "/assets/team/05_mario.jpeg",
  },
  {
    id: 6,
    name: "Yadira Galeano",
    linkedin: "https://www.linkedin.com/in/yadirdiazgaleano/",
    position_pt: "Advisor de Gestão de Risco e Continuidade do Negócio",
    position_en: "Risk Management and Business Continuity Advisor",
    photo: "/assets/team/06_yadira.jpeg",
  },
  {
    id: 7,
    name: "Marcos Tito",
    linkedin: "https://www.linkedin.com/in/mrctito/",
    position_pt: "Advisor de IA",
    position_en: "AI Advisor",
    photo: "/assets/team/07_marcos.jpeg",
  },
  {
    id: 8,
    name: "Danilo Melo",
    linkedin: "https://www.linkedin.com/in/danilo-melo-bb8586202/",
    position_pt: "Advisor de Estratégia",
    position_en: "Strategy Advisor",
    photo: "/assets/team/08_danilo.jpeg",
  },
  {
    id: 9,
    name: "Marco de Biasi",
    linkedin: "https://www.linkedin.com/in/debiasimarco/",
    position_pt: "Advisor de Investimentos",
    position_en: "Investment Advisor",
    photo: "/assets/team/09_marco.jpeg",
  },
  {
    id: 10,
    name: "Anand Kannan",
    linkedin: "https://www.linkedin.com/in/anand-kannan-24138b20a/",
    position_pt: "Head SGL India",
    position_en: "Head SGL India",
    photo: "/assets/team/10_anand.jpeg",
  },
];

export const verticalTypes: VerticalTypes[] = [
  {
    id: 1,
    value: "adtech",
    label_pt: "AdTech - Tecnologia de Publicidade",
    label_en: "AdTech - Advertising Technology",
  },
  {
    id: 2,
    value: "agritech",
    label_pt: "AgriTech - Tecnologia Agrícola",
    label_en: "AgriTech - Agricultural Technology",
  },
  {
    id: 3,
    value: "agtech",
    label_pt: "AgTech - Tecnologia Agrícola",
    label_en: "AgTech - Agricultural Technology",
  },
  {
    id: 4,
    value: "arvr",
    label_pt: "AR/VR - Realidade Aumentada/Realidade Virtual",
    label_en: "AR/VR - Augmented Reality/Virtual Reality",
  },
  {
    id: 5,
    value: "beautytech",
    label_pt: "BeautyTech - Tecnologia de Beleza",
    label_en: "BeautyTech - Beauty Technology",
  },
  {
    id: 6,
    value: "bigdata",
    label_pt: "Big Data - Grandes Dados e Análise de Dados",
    label_en: "Big Data - Big Data and Data Analysis",
  },
  {
    id: 7,
    value: "biotech",
    label_pt: "BioTech - Tecnologia de Biologia",
    label_en: "BioTech - Biotechnology",
  },
  {
    id: 8,
    value: "blockchain",
    label_pt: "Blockchain - Tecnologia de Blockchain",
    label_en: "Blockchain - Blockchain Technology",
  },
  {
    id: 9,
    value: "cleanenergy",
    label_pt: "Clean Energy - Energia Limpa",
    label_en: "Clean Energy - Clean Energy",
  },
  {
    id: 10,
    value: "cleantech",
    label_pt: "Cleantech - Tecnologia Limpa (sustentabilidade ambiental)",
    label_en: "Cleantech - Clean Technology (environmental sustainability)",
  },
  {
    id: 11,
    value: "cybersecurity",
    label_pt: "Cybersecurity - Segurança Cibernética",
    label_en: "Cybersecurity - Cybersecurity",
  },
  {
    id: 12,
    value: "datasecurity",
    label_pt: "Data Security - Segurança de Dados",
    label_en: "Data Security - Data Security",
  },
  {
    id: 13,
    value: "drones",
    label_pt: "Drones - Veículos Aéreos Não Tripulados",
    label_en: "Drones - Unmanned Aerial Vehicles",
  },
  {
    id: 14,
    value: "ecommerce",
    label_pt: "E-commerce - Comércio Eletrônico",
    label_en: "E-commerce - Electronic Commerce",
  },
  {
    id: 15,
    value: "ehealth",
    label_pt: "E-health - Tecnologia de Saúde Eletrônica",
    label_en: "E-health - Electronic Health Technology",
  },
  {
    id: 16,
    value: "editech",
    label_pt: "EdiTech - Tecnologia de Edição e Publicação",
    label_en: "EdiTech - Editing and Publishing Technology",
  },
  {
    id: 17,
    value: "edtech",
    label_pt: "EdTech - Tecnologia Educacional",
    label_en: "EdTech - Educational Technology",
  },
  {
    id: 18,
    value: "educationenvironmental",
    label_pt: "Educação Ambiental - Educação sobre Meio Ambiente",
    label_en: "Environmental Education - Environmental Education",
  },
  {
    id: 19,
    value: "energytech",
    label_pt: "EnergyTech - Tecnologia Energética",
    label_en: "EnergyTech - Energy Technology",
  },
  {
    id: 20,
    value: "fashiontech",
    label_pt: "FashionTech - Tecnologia de Moda",
    label_en: "FashionTech - Fashion Technology",
  },
  {
    id: 21,
    value: "fintech",
    label_pt: "Fintech - Tecnologia Financeira",
    label_en: "Fintech - Financial Technology",
  },
  {
    id: 22,
    value: "fitnesstech",
    label_pt: "FitnessTech - Tecnologia de Fitness",
    label_en: "FitnessTech - Fitness Technology",
  },
  {
    id: 23,
    value: "fooddelivery",
    label_pt: "Food Delivery - Entrega de Alimentos",
    label_en: "Food Delivery - Food Delivery",
  },
  {
    id: 24,
    value: "foodtech",
    label_pt: "Foodtech - Tecnologia Alimentar",
    label_en: "Foodtech - Food Technology",
  },
  {
    id: 25,
    value: "govtech",
    label_pt: "GovTech - Tecnologia Governamental",
    label_en: "GovTech - Government Technology",
  },
  {
    id: 26,
    value: "greentech",
    label_pt: "GreenTech - Tecnologia Sustentável",
    label_en: "GreenTech - Sustainable Technology",
  },
  {
    id: 27,
    value: "healthtech",
    label_pt: "Healthtech - Tecnologia de Saúde",
    label_en: "Healthtech - Health Technology",
  },
  {
    id: 28,
    value: "homeautomation",
    label_pt: "Home Automation - Automação Residencial",
    label_en: "Home Automation - Home Automation",
  },
  {
    id: 29,
    value: "hrtech",
    label_pt: "HRtech - Tecnologia de Recursos Humanos",
    label_en: "HRtech - Human Resources Technology",
  },
  {
    id: 30,
    value: "insurtech",
    label_pt: "Insurtech - Tecnologia de Seguros",
    label_en: "Insurtech - Insurance Technology",
  },
  {
    id: 31,
    value: "iot",
    label_pt: "IoT - Internet das Coisas",
    label_en: "IoT - Internet of Things",
  },
  {
    id: 32,
    value: "legaltech",
    label_pt: "Legaltech - Tecnologia Jurídica",
    label_en: "Legaltech - Legal Technology",
  },
  {
    id: 33,
    value: "marech",
    label_pt: "Marech - Tecnologia de Marketing",
    label_en: "Marech - Marketing Technology",
  },
  {
    id: 34,
    value: "medtech",
    label_pt: "Medtech - Tecnologia Médica",
    label_en: "Medtech - Medical Technology",
  },
  {
    id: 35,
    value: "mobileapp",
    label_pt: "Mobile App - Aplicativos Móveis",
    label_en: "Mobile App - Mobile Applications",
  },
  {
    id: 36,
    value: "mobilitytech",
    label_pt: "MobilityTech - Tecnologia de Mobilidade",
    label_en: "MobilityTech - Mobility Technology",
  },
  {
    id: 37,
    value: "musctech",
    label_pt: "MusicTech - Tecnologia Musical",
    label_en: "MusicTech - Music Technology",
  },
  {
    id: 38,
    value: "proptech",
    label_pt: "Proptech - Tecnologia Imobiliária",
    label_en: "Proptech - Real Estate Technology",
  },
  {
    id: 39,
    value: "retailtech",
    label_pt: "RetailTech - Tecnologia de Varejo",
    label_en: "RetailTech - Retail Technology",
  },
  {
    id: 40,
    value: "robotech",
    label_pt: "RoboTech - Tecnologia de Robótica",
    label_en: "RoboTech - Robotic Technology",
  },
  {
    id: 41,
    value: "saas",
    label_pt: "SaaS - Software como Serviço",
    label_en: "SaaS - Software as a Service",
  },
  {
    id: 42,
    value: "smartcitytech",
    label_pt: "Smart City Tech - Tecnologia para Cidades Inteligentes",
    label_en: "Smart City Tech - Technology for Smart Cities",
  },
  {
    id: 43,
    value: "socialmedia",
    label_pt: "Social Media - Mídias Sociais",
    label_en: "Social Media - Social Media",
  },
  {
    id: 44,
    value: "spaceexploration",
    label_pt: "Space Exploration - Exploração Espacial",
    label_en: "Space Exploration - Space Exploration",
  },
  {
    id: 45,
    value: "spacetech",
    label_pt: "SpaceTech - Tecnologia Espacial",
    label_en: "SpaceTech - Space Technology",
  },
  {
    id: 46,
    value: "sportstech",
    label_pt: "SportsTech - Tecnologia Esportiva",
    label_en: "SportsTech - Sports Technology",
  },
  {
    id: 47,
    value: "sustainability",
    label_pt: "Sustentabilidade - Startups focadas em práticas sustentáveis",
    label_en: "Sustainability - Startups focused on sustainable practices",
  },
  {
    id: 48,
    value: "traveltech",
    label_pt: "Traveltech - Tecnologia de Viagem",
    label_en: "Traveltech - Travel Technology",
  },
];

export const countriesList: CountriesList[] = [
  {
    id: 1,
    value: "afghanistan",
    label_en: "Afghanistan",
    label_pt: "Afeganistão",
  },
  {
    id: 2,
    value: "aland_islands",
    label_en: "Aland Islands",
    label_pt: "Ilhas Aland",
  },
  { id: 3, value: "albania", label_en: "Albania", label_pt: "Albânia" },
  { id: 4, value: "algeria", label_en: "Algeria", label_pt: "Argélia" },
  {
    id: 5,
    value: "american_samoa",
    label_en: "American Samoa",
    label_pt: "Samoa Americana",
  },
  { id: 6, value: "andorra", label_en: "Andorra", label_pt: "Andorra" },
  { id: 7, value: "angola", label_en: "Angola", label_pt: "Angola" },
  { id: 8, value: "anguilla", label_en: "Anguilla", label_pt: "Anguila" },
  { id: 9, value: "antarctica", label_en: "Antarctica", label_pt: "Antártida" },
  {
    id: 10,
    value: "antigua_and_barbuda",
    label_en: "Antigua and Barbuda",
    label_pt: "Antígua e Barbuda",
  },
  { id: 11, value: "argentina", label_en: "Argentina", label_pt: "Argentina" },
  { id: 12, value: "armenia", label_en: "Armenia", label_pt: "Armênia" },
  { id: 13, value: "aruba", label_en: "Aruba", label_pt: "Aruba" },
  { id: 14, value: "australia", label_en: "Australia", label_pt: "Austrália" },
  { id: 15, value: "austria", label_en: "Austria", label_pt: "Áustria" },
  {
    id: 16,
    value: "azerbaijan",
    label_en: "Azerbaijan",
    label_pt: "Azerbaijão",
  },
  { id: 17, value: "bahamas", label_en: "Bahamas", label_pt: "Bahamas" },
  { id: 18, value: "bahrain", label_en: "Bahrain", label_pt: "Bahrein" },
  {
    id: 19,
    value: "bangladesh",
    label_en: "Bangladesh",
    label_pt: "Bangladesh",
  },
  { id: 20, value: "barbados", label_en: "Barbados", label_pt: "Barbados" },
  { id: 21, value: "belarus", label_en: "Belarus", label_pt: "Bielorrússia" },
  { id: 22, value: "belgium", label_en: "Belgium", label_pt: "Bélgica" },
  { id: 23, value: "belize", label_en: "Belize", label_pt: "Belize" },
  { id: 24, value: "benin", label_en: "Benin", label_pt: "Benin" },
  { id: 25, value: "bermuda", label_en: "Bermuda", label_pt: "Bermudas" },
  { id: 26, value: "bhutan", label_en: "Bhutan", label_pt: "Butão" },
  { id: 27, value: "bolivia", label_en: "Bolivia", label_pt: "Bolívia" },
  {
    id: 28,
    value: "bosnia_and_herzegovina",
    label_en: "Bosnia and Herzegovina",
    label_pt: "Bósnia e Herzegovina",
  },
  { id: 29, value: "botswana", label_en: "Botswana", label_pt: "Botsuana" },
  {
    id: 30,
    value: "bouvet_island",
    label_en: "Bouvet Island",
    label_pt: "Ilha Bouvet",
  },
  { id: 31, value: "brazil", label_en: "Brazil", label_pt: "Brasil" },
  {
    id: 32,
    value: "british_indian_ocean_territory",
    label_en: "British Indian Ocean Territory",
    label_pt: "Território Britânico do Oceano Índico",
  },
  {
    id: 33,
    value: "brunei_darussalam",
    label_en: "Brunei Darussalam",
    label_pt: "Brunei",
  },
  { id: 34, value: "bulgaria", label_en: "Bulgaria", label_pt: "Bulgária" },
  {
    id: 35,
    value: "burkina_faso",
    label_en: "Burkina Faso",
    label_pt: "Burkina Faso",
  },
  { id: 36, value: "burundi", label_en: "Burundi", label_pt: "Burundi" },
  { id: 37, value: "cambodia", label_en: "Cambodia", label_pt: "Camboja" },
  { id: 38, value: "cameroon", label_en: "Cameroon", label_pt: "Camarões" },
  { id: 39, value: "canada", label_en: "Canada", label_pt: "Canadá" },
  {
    id: 40,
    value: "cape_verde",
    label_en: "Cape Verde",
    label_pt: "Cabo Verde",
  },
  {
    id: 41,
    value: "cayman_islands",
    label_en: "Cayman Islands",
    label_pt: "Ilhas Cayman",
  },
  {
    id: 42,
    value: "central_african_republic",
    label_en: "Central African Republic",
    label_pt: "República Centro-Africana",
  },
  { id: 43, value: "chad", label_en: "Chad", label_pt: "Chade" },
  { id: 44, value: "chile", label_en: "Chile", label_pt: "Chile" },
  { id: 45, value: "china", label_en: "China", label_pt: "China" },
  {
    id: 46,
    value: "christmas_island",
    label_en: "Christmas Island",
    label_pt: "Ilha Christmas",
  },
  {
    id: 47,
    value: "cocos_keeling_islands",
    label_en: "Cocos (Keeling) Islands",
    label_pt: "Ilhas Cocos (Keeling)",
  },
  { id: 48, value: "colombia", label_en: "Colombia", label_pt: "Colômbia" },
  { id: 49, value: "comoros", label_en: "Comoros", label_pt: "Comores" },
  { id: 50, value: "congo", label_en: "Congo", label_pt: "Congo" },
  {
    id: 51,
    value: "democratic_republic_of_the_congo",
    label_en: "Democratic Republic of the Congo",
    label_pt: "República Democrática do Congo",
  },
  {
    id: 52,
    value: "cook_islands",
    label_en: "Cook Islands",
    label_pt: "Ilhas Cook",
  },
  {
    id: 53,
    value: "costa_rica",
    label_en: "Costa Rica",
    label_pt: "Costa Rica",
  },
  {
    id: 54,
    value: "cote_divoire",
    label_en: "Cote D'Ivoire",
    label_pt: "Costa do Marfim",
  },
  { id: 55, value: "croatia", label_en: "Croatia", label_pt: "Croácia" },
  { id: 56, value: "cuba", label_en: "Cuba", label_pt: "Cuba" },
  { id: 57, value: "cyprus", label_en: "Cyprus", label_pt: "Chipre" },
  {
    id: 58,
    value: "czech_republic",
    label_en: "Czech Republic",
    label_pt: "República Tcheca",
  },
  { id: 59, value: "denmark", label_en: "Denmark", label_pt: "Dinamarca" },
  { id: 60, value: "djibouti", label_en: "Djibouti", label_pt: "Djibuti" },
  { id: 61, value: "dominica", label_en: "Dominica", label_pt: "Dominica" },
  {
    id: 62,
    value: "dominican_republic",
    label_en: "Dominican Republic",
    label_pt: "República Dominicana",
  },
  { id: 63, value: "ecuador", label_en: "Ecuador", label_pt: "Equador" },
  { id: 64, value: "egypt", label_en: "Egypt", label_pt: "Egito" },
  {
    id: 65,
    value: "el_salvador",
    label_en: "El Salvador",
    label_pt: "El Salvador",
  },
  {
    id: 66,
    value: "equatorial_guinea",
    label_en: "Equatorial Guinea",
    label_pt: "Guiné Equatorial",
  },
  { id: 67, value: "eritrea", label_en: "Eritrea", label_pt: "Eritreia" },
  { id: 68, value: "estonia", label_en: "Estonia", label_pt: "Estônia" },
  { id: 69, value: "ethiopia", label_en: "Ethiopia", label_pt: "Etiópia" },
  {
    id: 70,
    value: "falkland_islands_malvinas",
    label_en: "Falkland Islands (Malvinas)",
    label_pt: "Ilhas Falkland (Malvinas)",
  },
  {
    id: 71,
    value: "faroe_islands",
    label_en: "Faroe Islands",
    label_pt: "Ilhas Faroé",
  },
  { id: 72, value: "fiji", label_en: "Fiji", label_pt: "Fiji" },
  { id: 73, value: "finland", label_en: "Finland", label_pt: "Finlândia" },
  { id: 74, value: "france", label_en: "France", label_pt: "França" },
  {
    id: 75,
    value: "french_guiana",
    label_en: "French Guiana",
    label_pt: "Guiana Francesa",
  },
  {
    id: 76,
    value: "french_polynesia",
    label_en: "French Polynesia",
    label_pt: "Polinésia Francesa",
  },
  {
    id: 77,
    value: "french_southern_territories",
    label_en: "French Southern Territories",
    label_pt: "Territórios Franceses do Sul",
  },
  { id: 78, value: "gabon", label_en: "Gabon", label_pt: "Gabão" },
  { id: 79, value: "gambia", label_en: "Gambia", label_pt: "Gâmbia" },
  { id: 80, value: "georgia", label_en: "Georgia", label_pt: "Geórgia" },
  { id: 81, value: "germany", label_en: "Germany", label_pt: "Alemanha" },
  { id: 82, value: "ghana", label_en: "Ghana", label_pt: "Gana" },
  { id: 83, value: "gibraltar", label_en: "Gibraltar", label_pt: "Gibraltar" },
  { id: 84, value: "greece", label_en: "Greece", label_pt: "Grécia" },
  {
    id: 85,
    value: "greenland",
    label_en: "Greenland",
    label_pt: "Groenlândia",
  },
  { id: 86, value: "grenada", label_en: "Grenada", label_pt: "Granada" },
  {
    id: 87,
    value: "guadeloupe",
    label_en: "Guadeloupe",
    label_pt: "Guadalupe",
  },
  { id: 88, value: "guam", label_en: "Guam", label_pt: "Guam" },
  { id: 89, value: "guatemala", label_en: "Guatemala", label_pt: "Guatemala" },
  { id: 90, value: "guernsey", label_en: "Guernsey", label_pt: "Guernsey" },
  { id: 91, value: "guinea", label_en: "Guinea", label_pt: "Guiné" },
  {
    id: 92,
    value: "guinea_bissau",
    label_en: "Guinea-Bissau",
    label_pt: "Guiné-Bissau",
  },
  { id: 93, value: "guyana", label_en: "Guyana", label_pt: "Guiana" },
  { id: 94, value: "haiti", label_en: "Haiti", label_pt: "Haiti" },
  {
    id: 95,
    value: "heard_island_and_mcdonald_islands",
    label_en: "Heard Island and Mcdonald Islands",
    label_pt: "Ilha Heard e Ilhas McDonald",
  },
  {
    id: 96,
    value: "holy_see_vatican_city_state",
    label_en: "Holy See (Vatican City State)",
    label_pt: "Santa Sé (Estado da Cidade do Vaticano)",
  },
  { id: 97, value: "honduras", label_en: "Honduras", label_pt: "Honduras" },
  { id: 98, value: "hong_kong", label_en: "Hong Kong", label_pt: "Hong Kong" },
  { id: 99, value: "hungary", label_en: "Hungary", label_pt: "Hungria" },
  { id: 100, value: "iceland", label_en: "Iceland", label_pt: "Islândia" },
  { id: 101, value: "india", label_en: "India", label_pt: "Índia" },
  { id: 102, value: "indonesia", label_en: "Indonesia", label_pt: "Indonésia" },
  { id: 103, value: "iran", label_en: "Iran", label_pt: "Irã" },
  { id: 104, value: "iraq", label_en: "Iraq", label_pt: "Iraque" },
  { id: 105, value: "ireland", label_en: "Ireland", label_pt: "Irlanda" },
  {
    id: 106,
    value: "isle_of_man",
    label_en: "Isle of Man",
    label_pt: "Ilha de Man",
  },
  { id: 107, value: "israel", label_en: "Israel", label_pt: "Israel" },
  { id: 108, value: "italy", label_en: "Italy", label_pt: "Itália" },
  { id: 109, value: "jamaica", label_en: "Jamaica", label_pt: "Jamaica" },
  { id: 110, value: "japan", label_en: "Japan", label_pt: "Japão" },
  { id: 111, value: "jersey", label_en: "Jersey", label_pt: "Jersey" },
  { id: 112, value: "jordan", label_en: "Jordan", label_pt: "Jordânia" },
  {
    id: 113,
    value: "kazakhstan",
    label_en: "Kazakhstan",
    label_pt: "Cazaquistão",
  },
  { id: 114, value: "kenya", label_en: "Kenya", label_pt: "Quênia" },
  { id: 115, value: "kiribati", label_en: "Kiribati", label_pt: "Kiribati" },
  {
    id: 116,
    value: "north_korea",
    label_en: "North Korea",
    label_pt: "Coreia do Norte",
  },
  {
    id: 117,
    value: "south_korea",
    label_en: "South Korea",
    label_pt: "Coreia do Sul",
  },
  { id: 118, value: "kuwait", label_en: "Kuwait", label_pt: "Kuwait" },
  {
    id: 119,
    value: "kyrgyzstan",
    label_en: "Kyrgyzstan",
    label_pt: "Quirguistão",
  },
  { id: 120, value: "laos", label_en: "Laos", label_pt: "Laos" },
  { id: 121, value: "latvia", label_en: "Latvia", label_pt: "Letônia" },
  { id: 122, value: "lebanon", label_en: "Lebanon", label_pt: "Líbano" },
  { id: 123, value: "lesotho", label_en: "Lesotho", label_pt: "Lesoto" },
  { id: 124, value: "liberia", label_en: "Liberia", label_pt: "Libéria" },
  {
    id: 125,
    value: "libyan_arab_jamahiriya",
    label_en: "Libyan Arab Jamahiriya",
    label_pt: "Líbia",
  },
  {
    id: 126,
    value: "liechtenstein",
    label_en: "Liechtenstein",
    label_pt: "Liechtenstein",
  },
  { id: 127, value: "lithuania", label_en: "Lithuania", label_pt: "Lituânia" },
  {
    id: 128,
    value: "luxembourg",
    label_en: "Luxembourg",
    label_pt: "Luxemburgo",
  },
  { id: 129, value: "macao", label_en: "Macao", label_pt: "Macau" },
  { id: 130, value: "macedonia", label_en: "Macedonia", label_pt: "Macedônia" },
  {
    id: 131,
    value: "madagascar",
    label_en: "Madagascar",
    label_pt: "Madagáscar",
  },
  { id: 132, value: "malawi", label_en: "Malawi", label_pt: "Malawi" },
  { id: 133, value: "malaysia", label_en: "Malaysia", label_pt: "Malásia" },
  { id: 134, value: "maldives", label_en: "Maldives", label_pt: "Maldivas" },
  { id: 135, value: "mali", label_en: "Mali", label_pt: "Mali" },
  { id: 136, value: "malta", label_en: "Malta", label_pt: "Malta" },
  {
    id: 137,
    value: "marshall_islands",
    label_en: "Marshall Islands",
    label_pt: "Ilhas Marshall",
  },
  {
    id: 138,
    value: "martinique",
    label_en: "Martinique",
    label_pt: "Martinica",
  },
  {
    id: 139,
    value: "mauritania",
    label_en: "Mauritania",
    label_pt: "Mauritânia",
  },
  { id: 140, value: "mauritius", label_en: "Mauritius", label_pt: "Maurícia" },
  { id: 141, value: "mayotte", label_en: "Mayotte", label_pt: "Mayotte" },
  { id: 142, value: "mexico", label_en: "Mexico", label_pt: "México" },
  {
    id: 143,
    value: "micronesia",
    label_en: "Micronesia",
    label_pt: "Micronésia",
  },
  { id: 144, value: "moldova", label_en: "Moldova", label_pt: "Moldávia" },
  { id: 145, value: "monaco", label_en: "Monaco", label_pt: "Mônaco" },
  { id: 146, value: "mongolia", label_en: "Mongolia", label_pt: "Mongólia" },
  {
    id: 147,
    value: "montserrat",
    label_en: "Montserrat",
    label_pt: "Montserrat",
  },
  { id: 148, value: "morocco", label_en: "Morocco", label_pt: "Marrocos" },
  {
    id: 149,
    value: "mozambique",
    label_en: "Mozambique",
    label_pt: "Moçambique",
  },
  { id: 150, value: "myanmar", label_en: "Myanmar", label_pt: "Mianmar" },
  { id: 151, value: "namibia", label_en: "Namibia", label_pt: "Namíbia" },
  { id: 152, value: "nauru", label_en: "Nauru", label_pt: "Nauru" },
  { id: 153, value: "nepal", label_en: "Nepal", label_pt: "Nepal" },
  {
    id: 154,
    value: "netherlands",
    label_en: "Netherlands",
    label_pt: "Países Baixos",
  },
  {
    id: 155,
    value: "netherlands_antilles",
    label_en: "Netherlands Antilles",
    label_pt: "Antilhas Neerlandesas",
  },
  {
    id: 156,
    value: "new_caledonia",
    label_en: "New Caledonia",
    label_pt: "Nova Caledônia",
  },
  {
    id: 157,
    value: "new_zealand",
    label_en: "New Zealand",
    label_pt: "Nova Zelândia",
  },
  { id: 158, value: "nicaragua", label_en: "Nicaragua", label_pt: "Nicarágua" },
  { id: 159, value: "niger", label_en: "Niger", label_pt: "Níger" },
  { id: 160, value: "nigeria", label_en: "Nigeria", label_pt: "Nigéria" },
  { id: 161, value: "niue", label_en: "Niue", label_pt: "Niue" },
  {
    id: 162,
    value: "norfolk_island",
    label_en: "Norfolk Island",
    label_pt: "Ilha Norfolk",
  },
  {
    id: 163,
    value: "northern_mariana_islands",
    label_en: "Northern Mariana Islands",
    label_pt: "Ilhas Marianas do Norte",
  },
  { id: 164, value: "norway", label_en: "Norway", label_pt: "Noruega" },
  { id: 165, value: "oman", label_en: "Oman", label_pt: "Omã" },
  { id: 166, value: "pakistan", label_en: "Pakistan", label_pt: "Paquistão" },
  { id: 167, value: "palau", label_en: "Palau", label_pt: "Palau" },
  {
    id: 168,
    value: "palestinian",
    label_en: "Palestinian",
    label_pt: "Palestina",
  },
  { id: 169, value: "panama", label_en: "Panama", label_pt: "Panamá" },
  {
    id: 170,
    value: "papua_new_guinea",
    label_en: "Papua New Guinea",
    label_pt: "Papua Nova Guiné",
  },
  { id: 171, value: "paraguay", label_en: "Paraguay", label_pt: "Paraguai" },
  { id: 172, value: "peru", label_en: "Peru", label_pt: "Peru" },
  {
    id: 173,
    value: "philippines",
    label_en: "Philippines",
    label_pt: "Filipinas",
  },
  { id: 174, value: "pitcairn", label_en: "Pitcairn", label_pt: "Pitcairn" },
  { id: 175, value: "poland", label_en: "Poland", label_pt: "Polônia" },
  { id: 176, value: "portugal", label_en: "Portugal", label_pt: "Portugal" },
  {
    id: 177,
    value: "puerto_rico",
    label_en: "Puerto Rico",
    label_pt: "Porto Rico",
  },
  { id: 178, value: "qatar", label_en: "Qatar", label_pt: "Catar" },
  { id: 179, value: "reunion", label_en: "Reunion", label_pt: "Reunião" },
  { id: 180, value: "romania", label_en: "Romania", label_pt: "Romênia" },
  {
    id: 181,
    value: "russian_federation",
    label_en: "Russian Federation",
    label_pt: "Federação Russa",
  },
  { id: 182, value: "rwanda", label_en: "RWANDA", label_pt: "Ruanda" },
  {
    id: 183,
    value: "saint_helena",
    label_en: "Saint Helena",
    label_pt: "Santa Helena",
  },
  {
    id: 184,
    value: "saint_kitts_and_nevis",
    label_en: "Saint Kitts and Nevis",
    label_pt: "Saint Kitts e Nevis",
  },
  {
    id: 185,
    value: "saint_lucia",
    label_en: "Saint Lucia",
    label_pt: "Santa Lúcia",
  },
  {
    id: 186,
    value: "saint_pierre_and_miquelon",
    label_en: "Saint Pierre and Miquelon",
    label_pt: "Saint Pierre e Miquelon",
  },
  {
    id: 187,
    value: "saint_vincent_and_the_grenadines",
    label_en: "Saint Vincent and the Grenadines",
    label_pt: "São Vicente e Granadinas",
  },
  { id: 188, value: "samoa", label_en: "Samoa", label_pt: "Samoa" },
  {
    id: 189,
    value: "san_marino",
    label_en: "San Marino",
    label_pt: "San Marino",
  },
  {
    id: 190,
    value: "sao_tome_and_principe",
    label_en: "Sao Tome and Principe",
    label_pt: "São Tomé e Príncipe",
  },
  {
    id: 191,
    value: "saudi_arabia",
    label_en: "Saudi Arabia",
    label_pt: "Arábia Saudita",
  },
  { id: 192, value: "senegal", label_en: "Senegal", label_pt: "Senegal" },
  {
    id: 193,
    value: "serbia_and_montenegro",
    label_en: "Serbia and Montenegro",
    label_pt: "Sérvia e Montenegro",
  },
  {
    id: 194,
    value: "seychelles",
    label_en: "Seychelles",
    label_pt: "Seicheles",
  },
  {
    id: 195,
    value: "sierra_leone",
    label_en: "Sierra Leone",
    label_pt: "Serra Leoa",
  },
  { id: 196, value: "singapore", label_en: "Singapore", label_pt: "Singapura" },
  { id: 197, value: "slovakia", label_en: "Slovakia", label_pt: "Eslováquia" },
  { id: 198, value: "slovenia", label_en: "Slovenia", label_pt: "Eslovênia" },
  {
    id: 199,
    value: "solomon_islands",
    label_en: "Solomon Islands",
    label_pt: "Ilhas Salomão",
  },
  { id: 200, value: "somalia", label_en: "Somalia", label_pt: "Somália" },
  {
    id: 201,
    value: "south_africa",
    label_en: "South Africa",
    label_pt: "África do Sul",
  },
  {
    id: 202,
    value: "south_georgia_and_the_south_sandwich_islands",
    label_en: "South Georgia and the South Sandwich Islands",
    label_pt: "Geórgia do Sul e Ilhas Sandwich do Sul",
  },
  { id: 203, value: "spain", label_en: "Spain", label_pt: "Espanha" },
  { id: 204, value: "sri_lanka", label_en: "Sri Lanka", label_pt: "Sri Lanka" },
  { id: 205, value: "sudan", label_en: "Sudan", label_pt: "Sudão" },
  { id: 206, value: "suriname", label_en: "Suriname", label_pt: "Suriname" },
  {
    id: 207,
    value: "svalbard_and_jan_mayen",
    label_en: "Svalbard and Jan Mayen",
    label_pt: "Svalbard e Jan Mayen",
  },
  {
    id: 208,
    value: "swaziland",
    label_en: "Swaziland",
    label_pt: "Suazilândia",
  },
  { id: 209, value: "sweden", label_en: "Sweden", label_pt: "Suécia" },
  { id: 210, value: "switzerland", label_en: "Switzerland", label_pt: "Suíça" },
  {
    id: 211,
    value: "syrian_arab_republic",
    label_en: "Syrian Arab Republic",
    label_pt: "República Árabe Síria",
  },
  { id: 212, value: "taiwan", label_en: "Taiwan", label_pt: "Taiwan" },
  {
    id: 213,
    value: "tajikistan",
    label_en: "Tajikistan",
    label_pt: "Tajiquistão",
  },
  { id: 214, value: "tanzania", label_en: "Tanzania", label_pt: "Tanzânia" },
  { id: 215, value: "thailand", label_en: "Thailand", label_pt: "Tailândia" },
  {
    id: 216,
    value: "timor-leste",
    label_en: "Timor-Leste",
    label_pt: "Timor-Leste",
  },
  { id: 217, value: "togo", label_en: "Togo", label_pt: "Togo" },
  { id: 218, value: "tokelau", label_en: "Tokelau", label_pt: "Tokelau" },
  { id: 219, value: "tonga", label_en: "Tonga", label_pt: "Tonga" },
  {
    id: 220,
    value: "trinidad_and_tobago",
    label_en: "Trinidad and Tobago",
    label_pt: "Trindade e Tobago",
  },
  { id: 221, value: "tunisia", label_en: "Tunisia", label_pt: "Tunísia" },
  { id: 222, value: "turkey", label_en: "Turkey", label_pt: "Turquia" },
  {
    id: 223,
    value: "turkmenistan",
    label_en: "Turkmenistan",
    label_pt: "Turcomenistão",
  },
  {
    id: 224,
    value: "turks_and_caicos_islands",
    label_en: "Turks and Caicos Islands",
    label_pt: "Ilhas Turks e Caicos",
  },
  { id: 225, value: "tuvalu", label_en: "Tuvalu", label_pt: "Tuvalu" },
  { id: 226, value: "uganda", label_en: "Uganda", label_pt: "Uganda" },
  { id: 227, value: "ukraine", label_en: "Ukraine", label_pt: "Ucrânia" },
  {
    id: 228,
    value: "united_arab_emirates",
    label_en: "United Arab Emirates",
    label_pt: "Emirados Árabes Unidos",
  },
  {
    id: 229,
    value: "united_kingdom",
    label_en: "United Kingdom",
    label_pt: "Reino Unido",
  },
  {
    id: 230,
    value: "united_states",
    label_en: "United States",
    label_pt: "Estados Unidos",
  },
  {
    id: 231,
    value: "united_states_minor_outlying_islands",
    label_en: "United States Minor Outlying Islands",
    label_pt: "Ilhas Menores Distantes dos Estados Unidos",
  },
  { id: 232, value: "uruguay", label_en: "Uruguay", label_pt: "Uruguai" },
  {
    id: 233,
    value: "uzbekistan",
    label_en: "Uzbekistan",
    label_pt: "Uzbequistão",
  },
  { id: 234, value: "vanuatu", label_en: "Vanuatu", label_pt: "Vanuatu" },
  { id: 235, value: "venezuela", label_en: "Venezuela", label_pt: "Venezuela" },
  { id: 236, value: "viet_nam", label_en: "Viet Nam", label_pt: "Vietnã" },
  {
    id: 237,
    value: "virgin_islands_british",
    label_en: "Virgin Islands, British",
    label_pt: "Ilhas Virgens Britânicas",
  },
  {
    id: 238,
    value: "virgin_islands_us",
    label_en: "Virgin Islands, U.S.",
    label_pt: "Ilhas Virgens Americanas",
  },
  {
    id: 239,
    value: "wallis_and_futuna",
    label_en: "Wallis and Futuna",
    label_pt: "Wallis e Futuna",
  },
  {
    id: 240,
    value: "western_sahara",
    label_en: "Western Sahara",
    label_pt: "Saara Ocidental",
  },
  { id: 241, value: "yemen", label_en: "Yemen", label_pt: "Iémen" },
  { id: 242, value: "zambia", label_en: "Zambia", label_pt: "Zâmbia" },
  { id: 243, value: "zimbabwe", label_en: "Zimbabwe", label_pt: "Zimbábue" },
];

export const businessModelList: BusinessModel[] = [
  {
    id: 1,
    value: "b2b",
    label: "B2B",
  },
  {
    id: 2,
    value: "b2c",
    label: "B2C",
  },
  {
    id: 3,
    value: "b2e",
    label: "B2E",
  },
  {
    id: 4,
    value: "b2g",
    label: "B2G",
  },
  {
    id: 5,
    value: "b2b2c",
    label: "B2B2C",
  },
  {
    id: 6,
    value: "b2i",
    label: "B2I",
  },
];

export const operationalStageList: OperationalStage[] = [
  {
    id: 1,
    value: "ideation",
    label_en:
      "Ideation (initial phase where the business idea is developed and validated)",
    label_pt:
      "Ideação (fase inicial, em que a ideia de negócio é desenvolvida e validada)",
  },

  {
    id: 2,
    value: "validation",
    label_en:
      "Validation (phase where the product or service is tested in the market to verify its viability)",
    label_pt:
      "Validação (fase em que o produto ou serviço é testado no mercado para verificar se é viável)",
  },
  {
    id: 3,
    value: "operation",
    label_en:
      "Operation (phase where the startup is in operation and begins to generate revenue)",
    label_pt:
      "Operação (fase em que a startup está em funcionamento e começa a gerar receita)",
  },
  {
    id: 4,
    value: "traction",
    label_en:
      "Traction (phase where the startup starts to grow rapidly and attract investors)",
    label_pt:
      "Tração (fase em que a startup começa a crescer rapidamente e atrair investidores)",
  },
  {
    id: 5,
    value: "scale",
    label_en:
      "Scale (phase where the startup expands its business to new markets and becomes a mature company)",
    label_pt:
      "Escala (fase em que a startup expande seus negócios para novos mercados e se torna uma empresa madura)",
  },
];

export const startupChallengesList: ChallengesList[] = [
  {
    id: 1,
    value: "definition_and_validation",
    label_en: "Definition and validation of the business model",
    label_pt: "Definição e validação do modelo de negócios",
  },
  {
    id: 2,
    value: "financial_modeling",
    label_en: "Financial modeling",
    label_pt: "Modelagem financeira",
  },
  {
    id: 3,
    value: "company_valuation",
    label_en: "Company valuation",
    label_pt: "Valuation da empresa",
  },
  {
    id: 4,
    value: "pricing",
    label_en: "Pricing",
    label_pt: "Precificação",
  },
  {
    id: 5,
    value: "marketing",
    label_en: "Marketing",
    label_pt: "Marketing",
  },
  {
    id: 6,
    value: "digital_marketing",
    label_en: "Digital marketing",
    label_pt: "Marketing digital",
  },
  {
    id: 7,
    value: "b2b_sales",
    label_en: "B2B Sales",
    label_pt: "Vendas B2B",
  },
  {
    id: 8,
    value: "b2c_sales",
    label_en: "B2C Sales",
    label_pt: "Vendas B2C",
  },
  {
    id: 9,
    value: "b2g_sales",
    label_en: "B2G Sales",
    label_pt: "Vendas B2G",
  },
  {
    id: 10,
    value: "ecommerce",
    label_en: "E-commerce",
    label_pt: "E-commerce",
  },
  {
    id: 11,
    value: "operations",
    label_en: "Operations",
    label_pt: "Operações",
  },
  {
    id: 12,
    value: "product_development",
    label_en: "Product development",
    label_pt: "Desenvolvimento de produto",
  },
  {
    id: 13,
    value: "purchasing",
    label_en: "Purchasing",
    label_pt: "Compras",
  },
  {
    id: 14,
    value: "strategic_vision",
    label_en: "Strategic vision and company direction",
    label_pt: "Visão estratégica e direcionamento da empresa",
  },
  {
    id: 15,
    value: "building_relationships",
    label_en:
      "Building a network of relationships (partnerships, suppliers...)",
    label_pt:
      "Construção de rede de relacionamento (parcerias, fornecedores...)",
  },
  {
    id: 16,
    value: "access_public_financing",
    label_en: "Access to public financing",
    label_pt: "Acesso a financiamento público",
  },
  {
    id: 17,
    value: "access_private_financing",
    label_en: "Access to private financing",
    label_pt: "Acesso a financiamento privado",
  },
  {
    id: 18,
    value: "access_to_investors",
    label_en: "Access to investors",
    label_pt: "Acesso a investidores",
  },
  {
    id: 19,
    value: "negotiation_with_investors",
    label_en: "Negotiation with investors",
    label_pt: "Negociação com investidores",
  },
  {
    id: 20,
    value: "team_leadership",
    label_en: "Team leadership",
    label_pt: "Liderança de equipes",
  },
  {
    id: 21,
    value: "intellectual_property",
    label_en: "Intellectual property",
    label_pt: "Propriedade intelectual",
  },
  {
    id: 22,
    value: "legal",
    label_en: "Legal",
    label_pt: "Jurídico",
  },
  {
    id: 23,
    value: "internationalization",
    label_en: "Internationalization",
    label_pt: "Internacionalização",
  },
];

export const trlList: TRLList[] = [
  {
    id: 1,
    value: "trl_1",
    label_en:
      "TRL 1 - Initial Concept: At this stage, the technology is in the conceptual stage, with basic research, theoretical studies, and initial ideas",
    label_pt:
      "TRL 1 - Conceito Inicial: Nesta fase, a tecnologia está em estágio conceitual, com pesquisa de base, estudos teóricos e ideias iniciais",
  },
  {
    id: 2,
    value: "trl_2",
    label_en:
      "TRL 2 - Conceptual Discovery: The technology is evaluated for its feasibility, and initial concepts are tested in a controlled environment",
    label_pt:
      "TRL 2 - Descoberta Conceitual: A tecnologia é avaliada quanto à sua viabilidade, e conceitos iniciais são testados em ambiente controlado",
  },
  {
    id: 3,
    value: "trl_3",
    label_en:
      "TRL 3 - Proof of Concept: Concepts are demonstrated in a laboratory environment, proving that the idea can work in practice",
    label_pt:
      "TRL 3 - Prova de Conceito: Os conceitos são demonstrados em ambiente de laboratório, provando que a ideia pode funcionar na prática",
  },
  {
    id: 4,
    value: "trl_4",
    label_en:
      "TRL 4 - Laboratory Prototype: The technology is developed to the point where a functional prototype is created and tested in a laboratory environment",
    label_pt:
      "TRL 4 - Protótipo em Ambiente de Laboratório: A tecnologia é desenvolvida até o ponto em que um protótipo funcional é criado e testado em ambiente de laboratório",
  },
  {
    id: 5,
    value: "trl_5",
    label_en:
      "TRL 5 - Simulated Environment Prototype: The prototype is tested in a simulated environment, closer to real operating conditions",
    label_pt:
      "TRL 5 - Protótipo em Ambiente Simulado: O protótipo é testado em um ambiente simulado, mais próximo das condições reais de operação",
  },
  {
    id: 6,
    value: "trl_6",
    label_en:
      "TRL 6 - Real Environment Prototype: The prototype is tested in a real environment and representative operational conditions",
    label_pt:
      "TRL 6 - Protótipo em Ambiente Real: O protótipo é testado em ambiente real e condições operacionais representativas",
  },
  {
    id: 7,
    value: "trl_7",
    label_en:
      "TRL 7 - Operational Environment Demonstration: The technology is demonstrated in an operational environment, validating its operation in real situations",
    label_pt:
      "TRL 7 - Demonstração em Ambiente Operacional: A tecnologia é demonstrada em ambiente operacional, validando seu funcionamento em situações reais",
  },
  {
    id: 8,
    value: "trl_8",
    label_en:
      "TRL 8 - Pre-Commercial System: The technology is refined to meet commercial requirements and is ready for market launch",
    label_pt:
      "TRL 8 - Sistema Pré-Comercial: A tecnologia é refinada para atender a requisitos comerciais e está pronta para lançamento no mercado",
  },
  {
    id: 9,
    value: "trl_9",
    label_en:
      "TRL 9 - Operational System: The technology is in real use, proven, and widely adopted in the market",
    label_pt:
      "TRL 9 - Sistema em Operação: A tecnologia está em uso real, comprovada e amplamente adotada no mercado",
  },
];

export const serviceProductsList: ServiceProductsStartup[] = [
  {
    id: 1,
    value: "physical_product",
    label_en: "Physical product",
    label_pt: "Produto físico",
  },
  {
    id: 2,
    value: "digital_product",
    label_en: "Digital product",
    label_pt: "Produto digital",
  },
  {
    id: 3,
    value: "in_person_service",
    label_en: "In-person service",
    label_pt: "Serviço presencial",
  },
  {
    id: 4,
    value: "digital_service",
    label_en: "Digital service",
    label_pt: "Serviço digital",
  },
];

export const expertsEbook: ExpertsEbook[] = [
  {
    id: 1,
    title_en: "Expert Guide",
    title_pt: "Guia do Especialista",
    link_en:
      "https://drive.google.com/file/d/1oYKb-yEHQi5Zfit4T4cxNK9IiQJcMBdG/view?usp=sharing",
    link_pt:
      "https://drive.google.com/file/d/1BaocxLBhMYcrsikL0dOn0PxzRT9p2r3V/view?usp=sharing",
    img_en: "/assets/ebooks/01_ebook_experts_en.png",
    img_pt: "/assets/ebooks/01_ebook_experts_pt.png",
  },
];
