export interface StartupProps {
  id?: number;
  startup_name: string;
  logo: string | null;
  foundation_year: number | null;
  value_proposal: string;
  sgl_badge: string;
  last_update: string;
  vertical: string;
  business_model: string;
  country: string;
  flag: string;
}

export interface ExpertProps {
  id: number;
  name: string;
  last_name: string;
  linkedin: string;
  description_en: string | null;
  description_pt: string | null;
  languages_en: string;
  languages_pt: string;
  work_field_en: string;
  work_field_pt: string;
  country_en: string;
  country_pt: string;
  photo: string | null;
  flag: string;
}

type InfoFlags = {
  [key: string]: string;
};

export const startupsList: StartupProps[] = [
  {
    id: 1,
    startup_name: "Vaca Roxa",
    foundation_year: 2022,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "AgriTech",
    business_model: "B2B2C",
    country: "Brasil",
    logo: "/assets/startups/logos/01_vaca_roxa.jpg",
    flag: "brazil",
  },
  {
    id: 2,
    startup_name: "Grupo Gestão Saúde",
    foundation_year: 2023,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "SaaS",
    business_model: "B2B",
    country: "Brasil",
    logo: "/assets/startups/logos/02_grupo_gestao_saude.png",
    flag: "brazil",
  },
  {
    id: 3,
    startup_name: "DS7 BANK",
    foundation_year: 2021,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "FinTech",
    business_model: "B2B2C",
    country: "Brasil",
    logo: "/assets/startups/logos/03_ds7_bank.png",
    flag: "brazil",
  },
  {
    id: 4,
    startup_name: "mub",
    foundation_year: 2020,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "SaaS",
    business_model: "B2B",
    country: "Brasil",
    logo: "/assets/startups/logos/04_mub.png",
    flag: "brazil",
  },
  {
    id: 5,
    startup_name: "Meister Safe System",
    foundation_year: 2020,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "HealthTech",
    business_model: "B2B e B2C",
    country: "Brasil",
    logo: "/assets/startups/logos/05_meister_safe.jpg",
    flag: "brazil",
  },
  {
    id: 6,
    startup_name: "Vishv Foods and beverages LLP",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2C",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 7,
    startup_name: "Daksyam group",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 8,
    startup_name: "Agri Joy Pvt Ltd",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2C",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 9,
    startup_name: "Energysaver Business Solutions and Technology PVT LTD",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 10,
    startup_name: "DroneArch systems And Technologies Private Limited",
    foundation_year: 2023,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "Drones",
    business_model: "B2G",
    country: "India",
    logo: "/assets/startups/logos/10_dronearch.jpeg",
    flag: "india",
  },
  {
    id: 11,
    startup_name: "Curium Life Tech",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 12,
    startup_name: "MACHKG ICT LLP",
    foundation_year: 2022,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "IoTtech",
    business_model: "B2C",
    country: "India",
    logo: "/assets/startups/logos/12_machkg.png",
    flag: "india",
  },
  {
    id: 13,
    startup_name: "NANO BUBBLES BANGALORE Pvt Ltd",
    foundation_year: 2017,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "CleanTech",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/13_nano_bubbles.png",
    flag: "india",
  },
  {
    id: 14,
    startup_name: "Insignia Consultancy",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2C",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 15,
    startup_name: "Maathru health products",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 16,
    startup_name: "Hetrogenous Communication Technologies Pvt Ltd",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 17,
    startup_name: "PRESET Building Systems",
    foundation_year: 2023,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "PropeTech",
    business_model: "B2C",
    country: "India",
    logo: "/assets/startups/logos/17_preset_building.png",
    flag: "india",
  },
  {
    id: 18,
    startup_name: "INN-FORCE TECHNOLOGIES PRIVATE LIMITED",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 19,
    startup_name: "JALODBUST",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2C",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 20,
    startup_name: "Transfigure Technologies Pvt ltd",
    foundation_year: 2017,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "SaasTech",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/20_transfigure.png",
    flag: "india",
  },
  {
    id: 21,
    startup_name: "MetaBrix Labs",
    foundation_year: 2022,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "AI",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/21_metabrix.jpg",
    flag: "india",
  },
  {
    id: 22,
    startup_name: "GTO Pay Appz HR Solutions Private Limited",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 23,
    startup_name: "PAKSHIMITRA POULTRY TECHNOLOGIES PRIVATE LIMITED",
    foundation_year: 2018,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "AgriTech",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/23_pakshimitra.png",
    flag: "india",
  },
  {
    id: 24,
    startup_name: "Fabrik",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 25,
    startup_name: "Clear Water Dynamics Pvt Ltd",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2G",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 26,
    startup_name: "Life Bound Technologies Pvt Ltd",
    foundation_year: 2021,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "MedTech",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/26_life_bound.jpg",
    flag: "india",
  },
  {
    id: 27,
    startup_name: "ARFICUS PRIVATE LIMITED",
    foundation_year: 2019,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "HealthTech",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/27_arficus.jpg",
    flag: "india",
  },
  {
    id: 28,
    startup_name: "StatValu",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 29,
    startup_name: "Healthsure (M/S Kariakali Amman Foods Private Limited)",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "-",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 30,
    startup_name: "TECSMEN INNOVATION ",
    foundation_year: 2021,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "IoTtech",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/30_tecsmen.jpeg",
    flag: "india",
  },
  {
    id: 31,
    startup_name: "Sabhyasha Retail Tech Pvt Ltd.",
    foundation_year: 2022,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "E-commerce",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/31_sabhyasha.png",
    flag: "india",
  },
  {
    id: 32,
    startup_name: "Stocktick Capital",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2C",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 33,
    startup_name: "Offset Global Technologies Pvt Ltd",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 34,
    startup_name: "Manentia Ai",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 35,
    startup_name: "Nava Design and Innovation Pvt Ltd",
    foundation_year: 2016,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "AgriTech",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/35_nava.jpg",
    flag: "india",
  },
  {
    id: 36,
    startup_name: "ATTMANS",
    foundation_year: 2023,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/36_attmans.png",
    flag: "india",
  },
  {
    id: 37,
    startup_name: "VITT AI",
    foundation_year: 2017,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "FinTech",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/37_VITT.PNG",
    flag: "india",
  },
  {
    id: 38,
    startup_name: "Pentavalent Bio Sciences Private Limited",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 39,
    startup_name: "GFresh Agrotech Pvt Ltd",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 40,
    startup_name: "Vector Technics",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 41,
    startup_name: "CluCloud Innovations Pvt Ltd",
    foundation_year: 2022,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "FinTech",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/41_clucloud.jpg",
    flag: "india",
  },
  {
    id: 42,
    startup_name: "Veenero Sustainable Solutions",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 43,
    startup_name: "Aspalli Green Sustainable Ecosystem Pvt Ltd",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2G",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 44,
    startup_name: "Teakshed AI Pvt Ltd",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 45,
    startup_name: "Swayam Analytics Pvt Ltd",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 46,
    startup_name: "CANORX Motors Private Limited",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 47,
    startup_name: "Xecutables Ptv Ltd",
    foundation_year: 2020,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "HRTech",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/47_xecutables.png",
    flag: "india",
  },
  {
    id: 48,
    startup_name: "ProenX Pte. Ltd",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 49,
    startup_name: "Safsu",
    foundation_year: 2023,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "CleanTech",
    business_model: "B2C",
    country: "Finland",
    logo: "/assets/startups/logos/49_safsu.jpg",
    flag: "finland",
  },
  {
    id: 50,
    startup_name: "Austhraa motors private limited",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2C",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 51,
    startup_name: "Divine Campus Infotech Pvt Ltd",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 52,
    startup_name: "Dhanvantri Biomedical Private Limited",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2C",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 53,
    startup_name: "TechXcl India Pvt. Ltd",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 54,
    startup_name: "Qure.ai Technologies Private limited",
    foundation_year: 2019,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "HealthTech",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/54_qure.png",
    flag: "india",
  },
  {
    id: 55,
    startup_name: "Azooka Labs Pvt Ltd",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 56,
    startup_name: "Dentifrice Private Limited",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 57,
    startup_name: "HICET SUSTAINABLE SOLUTIONS PRIVATE LIMITED",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2G",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 58,
    startup_name: "SAPTKRISHI SCIENTIFIC PRIVATE LIMITED",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 59,
    startup_name: "Whrrl",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 60,
    startup_name: "ORGANIC MILE PRIVATE LIMITED",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 61,
    startup_name: "Xrathus, Inc.",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "USA",
    logo: null,
    flag: "usa",
  },
  {
    id: 62,
    startup_name: "Neidhal Cadet Service",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: null,
    flag: "india",
  },
  {
    id: 63,
    startup_name: "Uravu Labs Private Limited",
    foundation_year: null,
    value_proposal: "",
    sgl_badge: "junior",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "-",
    country: "India",
    logo: null,
    flag: "india",
  },
];

export const infoFlags: InfoFlags = {
  brazil: "/assets/flags/brazil.svg",
  colombia: "/assets/flags/colombia.svg",
  finland: "/assets/flags/finland.svg",
  india: "/assets/flags/india.svg",
  usa: "/assets/flags/usa.svg",
};

export const expertsList: ExpertProps[] = [
  {
    id: 1,
    name: "Yadira",
    last_name: "Galeano",
    linkedin: "https://www.linkedin.com/in/yadirdiazgaleano/",
    description_en:
      "I started my career as a business consultant, working on projects ranging from established companies to emerging ventures. Over the years, I have gained valuable skills in areas such as business strategy, financial analysis, process optimization, and team development. My passion for startups stems from the realization that they are true engines of innovation and disruption. The agility, creativity, and entrepreneurial mindset present in this environment have captivated me. Over time, I realized I wanted to direct my expertise to support visionary entrepreneurs in realizing their bold ideas.",
    description_pt:
      "Iniciei minha carreira como consultor de negócios, trabalhando em projetos que abrangem desde empresas estabelecidas até empreendimentos emergentes. Ao longo dos anos, adquiri habilidades valiosas em áreas como estratégia de negócios, análise financeira, otimização de processos e desenvolvimento de equipes. Minha paixão por startups surgiu da percepção de que são verdadeiros motores de inovação e disrupção. A agilidade, a criatividade e a mentalidade empreendedora presentes nesse ambiente me cativaram. Ao longo do tempo, percebi que queria direcionar minha expertise para apoiar empreendedores visionários na realização de suas ideias ousadas",
    languages_en: "pt - es",
    languages_pt: "pt - sp",
    work_field_en:
      "Partnerships, Internationalization, Leadership, Negotiation, Strategic Vision, Management",
    work_field_pt:
      "Parcerias, Internacionalização, Liderança, Negociação, Visão estratégica, Gestão",
    country_en: "Colombia",
    country_pt: "Colômbia",
    photo: "/assets/experts/01_yadira_galeano.png",
    flag: "colombia",
  },
  {
    id: 2,
    name: "Claudio",
    last_name: "de Souza",
    linkedin:
      "https://www.linkedin.com/in/claudio-alexandre-de-souza-cas-48709125/",
    description_en:
      "I have been working as a consultant for over 10 years for companies in the tourism, hospitality, and other sectors, as can be seen on the Xenios Institute website (www.xenios.org.br). I have been involved in mentoring for over 10 years in projects such as hackathons, NASA Space App, and as an innovation advisor for the hotel management startup Macna Digital Hotels.",
    description_pt:
      "Atua com consultoria há mais de 10 anos para empresas de turismo, hotelaria e outras que podem ser observada no site do Instituto Xenios (www.xenios.org.br). Atuo há mais de 10 anos com mentorias em projetos como hackathons , NASA Space App e como conselheiro para Inovação da startup de administração hoteleira Macna Digital Hotels.",
    languages_pt: "pt - es",
    languages_en: "pt - sp",
    work_field_pt: "Parcerias, Liderança, Operações",
    work_field_en: "Partnerships, Leadership, Operations",
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/02_claudio_alexandre_souza.jpeg",
    flag: "brazil",
  },
  {
    id: 3,
    name: "Felipe",
    last_name: "Seabra",
    linkedin: "Www.linkedin.com/in/felipedemouraseabra",
    description_en: "Internationalization and new business.",
    description_pt: "Internacionalização e novos negocios.",
    languages_en: "en - pt - sp",
    languages_pt: "in - pt - es",
    work_field_en:
      "Purchasing, Partnerships, Internationalization, Government Relations, B2B Sales",
    work_field_pt:
      "Compras, Parcerias, Internacionalização, Governos, Vendas B2B",
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/03_felipe_seabra.png",
    flag: "brazil",
  },
  {
    id: 4,
    name: "Samuel",
    last_name: "Magalhães",
    linkedin:
      "https://www.linkedin.com/in/samuel-magalh%C3%A3esc?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    description_en: null,
    description_pt: null,
    languages_en: "pt - en",
    languages_pt: "pt - in",
    work_field_en:
      "Financing, Business Model, Investors, Operations, Strategic Vision",
    work_field_pt:
      "Financiamentos, Modelo de negócios, Investidores, Operações, Visão estratégica",
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/04_samuel_magalhaes.jpg",
    flag: "brazil",
  },
  {
    id: 5,
    name: "Eduardo",
    last_name: "Balardim",
    linkedin: "https://www.linkedin.com/in/eduardobalardim",
    description_en:
      "I have over 17 years of experience in the Retail and Service sectors. I am part of the Retail vertical at Anjos do Brasil, where I work as a mentor and also as an angel investor. I am also a mentor for Inovativa Brasil, which is the largest startup acceleration program in Latin America.",
    description_pt:
      "Tenho mais de 17 anos atuando nas áreas de Varejo e Serviço. Faço parte da vertical de Varejo da Anjos do Brasil, onde atuo com mentoria e também como investidor anjo. Também sou mentor do Inovativa Brasil, que é o maior programa de aceleração de startups da América Latina.",
    languages_en: "en - pt - sp",
    languages_pt: "in - pt - es",
    work_field_en: "Business Model, Operations, Strategic Vision",
    work_field_pt: "Modelo de negócios, Operações, Visão estratégica",
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/05_eduardo_balardim.jpg",
    flag: "brazil",
  },
  {
    id: 6,
    name: "Guilherme",
    last_name: "Yata",
    linkedin: "http://linkedin.com/in/guilhermeyata",
    description_en:
      "I have extensive experience in the retail, engineering, and international business sectors with almost 30 years in this field. I am a member of the administrative boards of some startups here in Brazil. Additionally, I am a managing partner at S3 projects, where we develop energy transition projects for companies.",
    description_pt:
      "Tenho muita experiência na área de varejo, engenharia e negócios internacionais com quase 30 anos nessa área. Faço parte do conselho administrativos de algumas startups aqui no Brasil. Além disso sou sócio-diretor da S3 projects onde desenvolvemos projetos transição energética para empresas.",
    languages_en: "en - pt - sp",
    languages_pt: "in - pt - es",
    work_field_en:
      "Purchasing, Business Model, Product, Operations, Strategic Vision",
    work_field_pt:
      "Compras, Modelo de negócios, Produto, Operações, Visão estratégica",
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/06_guilherme_yata.jpeg",
    flag: "brazil",
  },
  {
    id: 7,
    name: "Simone",
    last_name: "Alves",
    linkedin:
      "https://www.linkedin.com/in/simonealvesrj?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    description_en:
      "As a consultant, I have experience in market research. With startups, I have been active since 2020 as a mentor and evaluator for various acceleration programs such as Inovativa Brasil, Inovativa de Impacto, Startup Conecta, Ela Empodera, Nexus Hub, CPS Inova, among others. I am also part of the Advisory Board of the startup Polimex Bioplásticos since 2021.",
    description_pt:
      "Como consultora tenho experiência em estudos de mercado. Com startups tenho atuado desde 2020 como mentora e avaliadora de diversos programas de aceleração como Inovativa Brasil, Inovativa de Impacto, Startup Conecta, Ela Empodera, Nexus Hub, CPS Inova, entre outros. Também sou do Conselho Consultivo ds startup Polimex Bioplásticos desde 2021",
    languages_en: "pt - en",
    languages_pt: "pt - in",
    work_field_en:
      "Public Funding, Business Model, Product, Marketing, B2B Sales",
    work_field_pt:
      "Financiamento público, Modelo de negócios, Produto, Marketing, Vendas B2B",
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/07_simone_alves.jpg",
    flag: "brazil",
  },
  {
    id: 8,
    name: "Rodrigo",
    last_name: "Grossi",
    linkedin: "https://www.linkedin.com/in/rodrigogrossi/",
    description_en:
      "I am Rodrigo, Founder of STARTUPS GLOBAL LINK, partner and Chief Technology Officer at 2mi Group, Startup Manager in the International Startup Program at IFIA, Advisor to two Startups, and Official Mentor of Inovativa Brasil. I founded TeamHub and bring valuable experience from ideation to exit. I was CTO at SOLIDES, and I also have experience in renowned corporations such as TOTVS and FCA.",
    description_pt:
      "Eu sou Rodrigo, sou Founder da STARTUPS GLOBAL LINK, sócio e Diretor Executivo de Tecnologia no grupo 2mi, Startup Manager no programa Internacional de Startups da IFIA, Advisor em duas Startups e Mentor Oficial do Inovativa Brasil. Fundei a TeamHub, e trago comigo a valiosa vivência desde a ideação até o exit. Fui CTO na SOLIDES, além de ter experiência em renomadas corporações como TOTVS e FCA.",
    languages_en: "pt - en",
    languages_pt: "pt - in",
    work_field_en: "Investors, Business Model, Leadership, Pricing, Valuation",
    work_field_pt:
      "Investidores, Modelo de negócios, Liderança, Precificação, Valuation",
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/08_rodrigo_grossi.jpeg",
    flag: "brazil",
  },
  {
    id: 9,
    name: "Marcos Tito",
    last_name: "Marques",
    linkedin: "https://www.linkedin.com/in/mrctito",
    description_en:
      "I am an Artificial Intelligence enthusiast with over 25 years of experience in the technology world, and my passion continues to grow. I am the kind of person who sees challenges as opportunities and learns by doing. My curiosity led me to develop an innovative AI product, and this self-instructive adventure has provided me with a wealth of practical knowledge in AI, as well as a profound understanding of its applications in the business world. Over the years, I have had the privilege of working with some of the largest software companies in the Brazilian and international markets, giving me a broad and diversified perspective of the industry. Leading multidisciplinary teams, including 100% remote teams, I have discovered the art of managing productivity and engagement from a distance. I firmly believe in the power of collaboration and communication to overcome obstacles and achieve ambitious goals. My experience spans various areas such as Education, Healthcare, Construction, HR, Hospitality, and more. I embrace both agile and traditional methodologies, and this flexibility allows me to adapt to different contexts and needs. In roles overseeing areas like Innovation, Support, Implementation, and Technology, I have developed a holistic vision that is crucial in software development.",
    description_pt:
      "Sou um entusiasta da Inteligência Artificial com mais de 25 anos de jornada no mundo da tecnologia, e minha paixão não para de crescer. Sou aquele tipo de pessoa que encara desafios como oportunidades e que aprende fazendo. Minha curiosidade me levou a desenvolver um produto de IA inovador, e essa aventura autoinstrutiva me trouxe um arsenal de conhecimentos práticos em IA, bem como uma compreensão profunda de suas aplicações no mundo dos negócios. Através dos anos, tive o privilégio de trabalhar com algumas das maiores empresas de software do mercado brasileiro e internacional, o que me proporcionou uma visão ampla e diversificada da indústria. Na liderança de equipes multidisciplinares, inclusive times 100% remotos, descobri a arte de gerenciar produtividade e engajamento à distância. Acredito firmemente no poder da colaboração e da comunicação para superar obstáculos e alcançar metas ambiciosas. Minha experiência se estende por áreas variadas como Educação, Saúde, Construção, RH, Hotelaria e muito mais. Sou adepto das metodologias ágeis e tradicionais, e essa flexibilidade me permite adaptar-me a diferentes contextos e necessidades. No comando de áreas como Inovação, Suporte, Implantação e Tecnologia, desenvolvi uma visão holística que é crucial no desenvolvimento de software.",
    languages_en: "pt",
    languages_pt: "pt",
    work_field_en:
      "Partnerships, Business Model, Product, Leadership, B2B Sales, Strategic Vision, Company Direction",
    work_field_pt:
      "Parcerias, Modelo de negócios, Produto, Liderança, Vendas B2B, Visão estratégica, Direcionamento da empresa",
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/09_marcos_tito.jpeg",
    flag: "brazil",
  },
  {
    id: 10,
    name: "Andre",
    last_name: "Bretas",
    linkedin: "https://www.linkedin.com/in/andrebretas",
    description_en:
      "I work as a partner in startups and have previously served as CTO and COO in others I've been involved with. Additionally, I have experience in large corporations.",
    description_pt:
      "Atuo como sócio em startups e já atuei com CTO e COO em outras que passei. Além disso já tive experiência em grandes corporações.",
    languages_en: "pt - en",
    languages_pt: "pt - in",
    work_field_en:
      "Business Model, Product, E-commerce, Leadership, Digital Marketing",
    work_field_pt:
      "Modelo de negócios, Produto, E-commerce, Liderança, Marketing digital",
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/10_andre_bretas.jpeg",
    flag: "brazil",
  },
];
