export interface StartupProps {
  id?: number;
  startup_name: string;
  logo: string | null;
  foundation_year: number | null;
  value_proposal_en: string;
  value_proposal_pt: string;
  last_update: string;
  vertical: string;
  business_model: string;
  country: string;
  flag: string;
}

export interface ExpertProps {
  id: number;
  name: string;
  last_name: string;
  linkedin: string;
  description_en: string | null;
  description_pt: string | null;
  languages_en: string;
  languages_pt: string;
  languages_en_array: string[];
  languages_pt_array: string[];
  work_field_en: string[];
  work_field_pt: string[];
  country_en: string;
  country_pt: string;
  photo: string | null;
  flag: string;
}

export interface TeamProps {
  id: number;
  name: string;
  linkedin: string;
  position_pt: string;
  position_en: string;
  photo: string;
}

export interface BannersProps {
  investors_banner_en: string;
  investors_banner_pt: string;
  main_banner_en: string;
  main_banner_pt: string;
  main_banner_mobile_en: string;
  main_banner_mobile_pt: string;
  mentors_banner_en: string;
  mentors_banner_pt: string;
  startups_banner_en: string;
  startups_banner_pt: string;
}

export const startupsList: StartupProps[] = [
  {
    id: 1,
    startup_name: "Vaca Roxa",
    foundation_year: 2022,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "AgriTech",
    business_model: "B2B2C",
    country: "Brasil",
    logo: "/assets/startups/logos/01_vaca_roxa.jpg",
    flag: "brazil",
  },
  {
    id: 2,
    startup_name: "Grupo Gestão Saúde",
    foundation_year: 2023,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "SaaS",
    business_model: "B2B",
    country: "Brasil",
    logo: "/assets/startups/logos/02_grupo_gestao_saude.png",
    flag: "brazil",
  },
  {
    id: 3,
    startup_name: "DS7 BANK",
    foundation_year: 2021,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "FinTech",
    business_model: "B2B2C",
    country: "Brasil",
    logo: "/assets/startups/logos/03_ds7_bank.png",
    flag: "brazil",
  },
  {
    id: 4,
    startup_name: "mub",
    foundation_year: 2020,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "SaaS",
    business_model: "B2B",
    country: "Brasil",
    logo: "/assets/startups/logos/04_mub.png",
    flag: "brazil",
  },
  {
    id: 5,
    startup_name: "Meister Safe System",
    foundation_year: 2020,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "HealthTech",
    business_model: "B2B e B2C",
    country: "Brasil",
    logo: "/assets/startups/logos/05_meister_safe.jpg",
    flag: "brazil",
  },
  {
    id: 6,
    startup_name: "Vishv Foods and beverages LLP",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2C",
    country: "India",
    logo: "/assets/startups/logos/06_vishv_foods.png",
    flag: "india",
  },
  {
    id: 7,
    startup_name: "Daksyam group",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/07_daksyam.png",
    flag: "india",
  },
  {
    id: 8,
    startup_name: "Agri Joy Pvt Ltd",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2C",
    country: "India",
    logo: "/assets/startups/logos/08_agri.png",
    flag: "india",
  },
  {
    id: 9,
    startup_name: "Energysaver Business Solutions and Technology PVT LTD",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/09_energysaver.png",
    flag: "india",
  },
  {
    id: 10,
    startup_name: "DroneArch systems And Technologies Private Limited",
    foundation_year: 2023,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "Drones",
    business_model: "B2G",
    country: "India",
    logo: "/assets/startups/logos/10_dronearch.jpeg",
    flag: "india",
  },
  {
    id: 11,
    startup_name: "Curium Life Tech",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/11_curium.png",
    flag: "india",
  },
  {
    id: 12,
    startup_name: "MACHKG ICT LLP",
    foundation_year: 2022,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "IoTtech",
    business_model: "B2C",
    country: "India",
    logo: "/assets/startups/logos/12_machkg.png",
    flag: "india",
  },
  {
    id: 13,
    startup_name: "NANO BUBBLES BANGALORE Pvt Ltd",
    foundation_year: 2017,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "CleanTech",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/13_nano_bubbles.png",
    flag: "india",
  },
  {
    id: 14,
    startup_name: "Insignia Consultancy",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2C",
    country: "India",
    logo: "/assets/startups/logos/14_insignia.png",
    flag: "india",
  },
  {
    id: 15,
    startup_name: "Maathru health products",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/15_maathru.png",
    flag: "india",
  },
  {
    id: 16,
    startup_name: "Hetrogenous Communication Technologies Pvt Ltd",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/16_hetrogenous.png",
    flag: "india",
  },
  {
    id: 17,
    startup_name: "PRESET Building Systems",
    foundation_year: 2023,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "PropeTech",
    business_model: "B2C",
    country: "India",
    logo: "/assets/startups/logos/17_preset_building.png",
    flag: "india",
  },
  {
    id: 18,
    startup_name: "INN-FORCE TECHNOLOGIES PRIVATE LIMITED",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/18_inn-force.png",
    flag: "india",
  },
  {
    id: 19,
    startup_name: "JALODBUST",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2C",
    country: "India",
    logo: "/assets/startups/logos/19_jalodbust.png",
    flag: "india",
  },
  {
    id: 20,
    startup_name: "Transfigure Technologies Pvt ltd",
    foundation_year: 2017,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "SaasTech",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/20_transfigure.png",
    flag: "india",
  },
  {
    id: 21,
    startup_name: "MetaBrix Labs",
    foundation_year: 2022,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "AI",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/21_metabrix.jpg",
    flag: "india",
  },
  {
    id: 22,
    startup_name: "GTO Pay Appz HR Solutions Private Limited",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/22_gto_pay.png",
    flag: "india",
  },
  {
    id: 23,
    startup_name: "PAKSHIMITRA POULTRY TECHNOLOGIES PRIVATE LIMITED",
    foundation_year: 2018,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "AgriTech",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/23_pakshimitra.png",
    flag: "india",
  },
  {
    id: 24,
    startup_name: "Fabrik",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/24_fabrik.png",
    flag: "india",
  },
  {
    id: 25,
    startup_name: "Clear Water Dynamics Pvt Ltd",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2G",
    country: "India",
    logo: "/assets/startups/logos/25_clear_water.png",
    flag: "india",
  },
  {
    id: 26,
    startup_name: "Life Bound Technologies Pvt Ltd",
    foundation_year: 2021,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "MedTech",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/26_life_bound.jpg",
    flag: "india",
  },
  {
    id: 27,
    startup_name: "ARFICUS PRIVATE LIMITED",
    foundation_year: 2019,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "HealthTech",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/27_arficus.jpg",
    flag: "india",
  },
  {
    id: 28,
    startup_name: "StatValu",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/28_statvalu.png",
    flag: "india",
  },
  {
    id: 29,
    startup_name: "Healthsure (M/S Kariakali Amman Foods Private Limited)",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "-",
    country: "India",
    logo: "/assets/startups/logos/29_healthsure.png",
    flag: "india",
  },
  {
    id: 30,
    startup_name: "TECSMEN INNOVATION ",
    foundation_year: 2021,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "IoTtech",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/30_tecsmen.jpeg",
    flag: "india",
  },
  {
    id: 31,
    startup_name: "Sabhyasha Retail Tech Pvt Ltd.",
    foundation_year: 2022,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "E-commerce",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/31_sabhyasha.png",
    flag: "india",
  },
  {
    id: 32,
    startup_name: "Stocktick Capital",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2C",
    country: "India",
    logo: "/assets/startups/logos/32_stocktick.png",
    flag: "india",
  },
  {
    id: 33,
    startup_name: "Offset Global Technologies Pvt Ltd",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/33_offset_global.png",
    flag: "india",
  },
  {
    id: 34,
    startup_name: "Manentia Ai",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/34_manentia.png",
    flag: "india",
  },
  {
    id: 35,
    startup_name: "Nava Design and Innovation Pvt Ltd",
    foundation_year: 2016,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "AgriTech",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/35_nava.jpg",
    flag: "india",
  },
  {
    id: 36,
    startup_name: "ATTMANS",
    foundation_year: 2023,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/36_attmans.png",
    flag: "india",
  },
  {
    id: 37,
    startup_name: "VITT AI",
    foundation_year: 2017,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "FinTech",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/37_vitt.png",
    flag: "india",
  },
  {
    id: 38,
    startup_name: "Pentavalent Bio Sciences Private Limited",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/38_pentavalent.png",
    flag: "india",
  },
  {
    id: 39,
    startup_name: "GFresh Agrotech Pvt Ltd",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/39_gfresh.png",
    flag: "india",
  },
  {
    id: 40,
    startup_name: "Vector Technics",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/40_vector.png",
    flag: "india",
  },
  {
    id: 41,
    startup_name: "CluCloud Innovations Pvt Ltd",
    foundation_year: 2022,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "FinTech",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/41_clucloud.jpg",
    flag: "india",
  },
  {
    id: 42,
    startup_name: "Veenero Sustainable Solutions",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/42_veenero.png",
    flag: "india",
  },
  {
    id: 43,
    startup_name: "Aspalli Green Sustainable Ecosystem Pvt Ltd",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2G",
    country: "India",
    logo: "/assets/startups/logos/43_aspalli.png",
    flag: "india",
  },
  {
    id: 44,
    startup_name: "Teakshed AI Pvt Ltd",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/44_teakshed.png",
    flag: "india",
  },
  {
    id: 45,
    startup_name: "Swayam Analytics Pvt Ltd",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/45_swayam.png",
    flag: "india",
  },
  {
    id: 46,
    startup_name: "CANORX Motors Private Limited",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/46_canorx.png",
    flag: "india",
  },
  {
    id: 47,
    startup_name: "Xecutables Ptv Ltd",
    foundation_year: 2020,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "HRTech",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/47_xecutables.png",
    flag: "india",
  },
  {
    id: 48,
    startup_name: "ProenX Pte. Ltd",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/48_proenx.png",
    flag: "india",
  },
  {
    id: 49,
    startup_name: "Safsu",
    foundation_year: 2023,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "CleanTech",
    business_model: "B2C",
    country: "Finland",
    logo: "/assets/startups/logos/49_safsu.jpg",
    flag: "finland",
  },
  {
    id: 50,
    startup_name: "Austhraa motors private limited",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2C",
    country: "India",
    logo: "/assets/startups/logos/50_austhraa.png",
    flag: "india",
  },
  {
    id: 51,
    startup_name: "Divine Campus Infotech Pvt Ltd",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/51_divine.png",
    flag: "india",
  },
  {
    id: 52,
    startup_name: "Dhanvantri Biomedical Private Limited",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2C",
    country: "India",
    logo: "/assets/startups/logos/52_dhanvantri.png",
    flag: "india",
  },
  {
    id: 53,
    startup_name: "TechXcl India Pvt. Ltd",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/53_techxcl.png",
    flag: "india",
  },
  {
    id: 54,
    startup_name: "Qure.ai Technologies Private limited",
    foundation_year: 2019,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "HealthTech",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/54_qure.png",
    flag: "india",
  },
  {
    id: 55,
    startup_name: "Azooka Labs Pvt Ltd",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/55_azooka.png",
    flag: "india",
  },
  {
    id: 56,
    startup_name: "Dentifrice Private Limited",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/56_dentifrice.png",
    flag: "india",
  },
  {
    id: 57,
    startup_name: "HICET SUSTAINABLE SOLUTIONS PRIVATE LIMITED",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2G",
    country: "India",
    logo: "/assets/startups/logos/57_hicet.png",
    flag: "india",
  },
  {
    id: 58,
    startup_name: "SAPTKRISHI SCIENTIFIC PRIVATE LIMITED",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/58_saptkrishi.png",
    flag: "india",
  },
  {
    id: 59,
    startup_name: "Whrrl",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/59_whrrl.png",
    flag: "india",
  },
  {
    id: 60,
    startup_name: "ORGANIC MILE PRIVATE LIMITED",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/60_organic_mile.png",
    flag: "india",
  },
  {
    id: 61,
    startup_name: "Xrathus, Inc.",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B",
    country: "USA",
    logo: "/assets/startups/logos/61_xrathus.png",
    flag: "usa",
  },
  {
    id: 62,
    startup_name: "Neidhal Cadet Service",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/62_neidhal.png",
    flag: "india",
  },
  {
    id: 63,
    startup_name: "Uravu Labs Private Limited",
    foundation_year: null,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "-",
    business_model: "-",
    country: "India",
    logo: "/assets/startups/logos/63_uravu.png",
    flag: "india",
  },
  {
    id: 64,
    startup_name: "E-Veritas Energia",
    foundation_year: 2023,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "EdTech",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/64_everitas.png",
    flag: "india",
  },
  {
    id: 65,
    startup_name: "Empresasecia",
    foundation_year: 2019,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "E-healfth",
    business_model: "B2C",
    country: "Brasil",
    logo: "/assets/startups/logos/65_empresasecia.jpg",
    flag: "brazil",
  },
  {
    id: 66,
    startup_name: "SagaPro Edtech Ltda",
    foundation_year: 2021,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "10/01/2024",
    vertical: "EdTech",
    business_model: "B2B",
    country: "Brasil",
    logo: "/assets/startups/logos/66_sagapro.png",
    flag: "brazil",
  },
  {
    id: 67,
    startup_name: "Meu Cuidador - Marketplace de Soluções em Saúde",
    foundation_year: 2020,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "21/01/2024",
    vertical: "HealthTech",
    business_model: "B2B2C",
    country: "Brasil",
    logo: "/assets/startups/logos/67_meu_cuidador.jpeg",
    flag: "brazil",
  },
  {
    id: 68,
    startup_name: "Sabhyasha Retail Tech Pvt. Ltd.",
    foundation_year: 2022,
    value_proposal_en:
      "Linking Artisans & Markets; Diverse Crafts, Empowerment, AI-Enhanced",
    value_proposal_pt:
      "Conectando Artesãos e Mercados; Artes Diversas, Empoderamento, Aprimorado por IA",
    last_update: "05/02/2024",
    vertical: "RetailTech - Tecnologia de Varejo",
    business_model: "B2B2C",
    country: "India",
    logo: "/assets/startups/logos/68_babhyasha.jpg",
    flag: "india",
  },
  {
    id: 69,
    startup_name: "Meister Safe System",
    foundation_year: 2020,
    value_proposal_en: "We take care of the air you breathe",
    value_proposal_pt: "Cuidamos do ar que você respira",
    last_update: "05/02/2024",
    vertical: "Healthtech - Tecnologia de Saúde",
    business_model: "B2B",
    country: "Brasil",
    logo: "/assets/startups/logos/69_meister_safe.jpg",
    flag: "brazil",
  },
  {
    id: 70,
    startup_name: "mub - Sistema de Gestão de Workflows",
    foundation_year: 2020,
    value_proposal_en:
      "Total control, simplified management, operational efficiency",
    value_proposal_pt:
      "Controle total, gestão simplificada, eficiência operacional",
    last_update: "05/02/2024",
    vertical: "SaaS - Software como Serviço",
    business_model: "B2B",
    country: "Brasil",
    logo: "/assets/startups/logos/70_mub.png",
    flag: "brazil",
  },
  {
    id: 71,
    startup_name: "AQUi9",
    foundation_year: 2022,
    value_proposal_en:
      "Increase productivity, profitability, and operational efficiency",
    value_proposal_pt:
      "Aumentar a produtividade, lucratividade e a eficiência operacional",
    last_update: "05/02/2024",
    vertical: "AgTech - Tecnologia Agrícola",
    business_model: "B2B",
    country: "Brasil",
    logo: "/assets/startups/logos/71_aqui9.png",
    flag: "brazil",
  },
  {
    id: 72,
    startup_name: "PRESET BUILDING SYSTEMS PVT LTD",
    foundation_year: 2023,
    value_proposal_en: "",
    value_proposal_pt: "",
    last_update: "05/02/2024",
    vertical: "PropeTech - real estate technology",
    business_model: "B2C",
    country: "India",
    logo: "/assets/startups/logos/72_hamsa.png",
    flag: "india",
  },
  {
    id: 73,
    startup_name: "Avas DigiTech",
    foundation_year: 2020,
    value_proposal_en: "Smaarket: Empowering Investors, Elevating Startups",
    value_proposal_pt: "Smaarket: Empoderando Investidores, Elevando Startups",
    last_update: "05/02/2024",
    vertical: "FinTech-financial technologies",
    business_model: "B2B",
    country: "India",
    logo: "/assets/startups/logos/73_avas_digitech.jpg",
    flag: "india",
  },
];

export const expertsList: ExpertProps[] = [
  {
    id: 1,
    name: "Yadira",
    last_name: "Galeano",
    linkedin: "https://www.linkedin.com/in/yadirdiazgaleano/",
    description_en:
      "I started my career as a business consultant, working on projects ranging from established companies to emerging ventures. Over the years, I have gained valuable skills in areas such as business strategy, financial analysis, process optimization, and team development. My passion for startups stems from the realization that they are true engines of innovation and disruption. The agility, creativity, and entrepreneurial mindset present in this environment have captivated me. Over time, I realized I wanted to direct my expertise to support visionary entrepreneurs in realizing their bold ideas.",
    description_pt:
      "Iniciei minha carreira como consultor de negócios, trabalhando em projetos que abrangem desde empresas estabelecidas até empreendimentos emergentes. Ao longo dos anos, adquiri habilidades valiosas em áreas como estratégia de negócios, análise financeira, otimização de processos e desenvolvimento de equipes. Minha paixão por startups surgiu da percepção de que são verdadeiros motores de inovação e disrupção. A agilidade, a criatividade e a mentalidade empreendedora presentes nesse ambiente me cativaram. Ao longo do tempo, percebi que queria direcionar minha expertise para apoiar empreendedores visionários na realização de suas ideias ousadas",
    languages_en: "pt - sp",
    languages_pt: "pt - es",
    languages_en_array: ["Portuguese", "Spanish"],
    languages_pt_array: ["Português", "Espanhol"],
    work_field_en: [
      "Partnerships",
      "Internationalization",
      "Leadership",
      "Negotiation",
      "Strategic Vision",
      "Management",
    ],
    work_field_pt: [
      "Parcerias",
      "Internacionalização",
      "Liderança",
      "Negociação",
      "Visão estratégica",
      "Gestão",
    ],
    country_en: "Colombia",
    country_pt: "Colômbia",
    photo: "/assets/experts/01_yadira_galeano.png",
    flag: "colombia",
  },
  {
    id: 2,
    name: "Claudio",
    last_name: "de Souza",
    linkedin:
      "https://www.linkedin.com/in/claudio-alexandre-de-souza-cas-48709125/",
    description_en:
      "I have been working as a consultant for over 10 years for companies in the tourism, hospitality, and other sectors, as can be seen on the Xenios Institute website (www.xenios.org.br). I have been involved in mentoring for over 10 years in projects such as hackathons, NASA Space App, and as an innovation advisor for the hotel management startup Macna Digital Hotels.",
    description_pt:
      "Atua com consultoria há mais de 10 anos para empresas de turismo, hotelaria e outras que podem ser observada no site do Instituto Xenios (www.xenios.org.br). Atuo há mais de 10 anos com mentorias em projetos como hackathons, NASA Space App e como conselheiro para Inovação da startup de administração hoteleira Macna Digital Hotels.",
    languages_en: "pt - sp",
    languages_pt: "pt - es",
    languages_en_array: ["Portuguese", "Spanish"],
    languages_pt_array: ["Português", "Espanhol"],
    work_field_pt: ["Parcerias", "Liderança", "Operações"],
    work_field_en: ["Partnerships", "Leadership", "Operations"],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/02_claudio_alexandre_souza.jpeg",
    flag: "brazil",
  },
  {
    id: 3,
    name: "Felipe",
    last_name: "Seabra",
    linkedin: "Www.linkedin.com/in/felipedemouraseabra",
    description_en: "Internationalization and new business.",
    description_pt: "Internacionalização e novos negocios.",
    languages_en: "en - pt - sp",
    languages_pt: "in - pt - es",
    languages_en_array: ["English", "Portuguese", "Spanish"],
    languages_pt_array: ["Inglês", "Português", "Espanhol"],
    work_field_en: [
      "Purchasing",
      "Partnerships",
      "Internationalization",
      "Government Relations",
      "B2B Sales",
    ],
    work_field_pt: [
      "Compras",
      "Parcerias",
      "Internacionalização",
      "Governos",
      "Vendas B2B",
    ],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/03_felipe_seabra.png",
    flag: "brazil",
  },
  {
    id: 4,
    name: "Samuel",
    last_name: "Magalhães",
    linkedin:
      "https://www.linkedin.com/in/samuel-magalh%C3%A3esc?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    description_en: null,
    description_pt: null,
    languages_en: "pt - en",
    languages_pt: "pt - in",
    languages_en_array: ["Portuguese", "English"],
    languages_pt_array: ["Português", "Inglês"],
    work_field_en: [
      "Financing",
      "Business Model",
      "Investors",
      "Operations",
      "Strategic Vision",
    ],
    work_field_pt: [
      "Financiamentos",
      "Modelo de negócios",
      "Investidores",
      "Operações",
      "Visão estratégica",
    ],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/04_samuel_magalhaes.jpg",
    flag: "brazil",
  },
  {
    id: 5,
    name: "Eduardo",
    last_name: "Balardim",
    linkedin: "https://www.linkedin.com/in/eduardobalardim",
    description_en:
      "I have over 17 years of experience in the Retail and Service sectors. I am part of the Retail vertical at Anjos do Brasil, where I work as a mentor and also as an angel investor. I am also a mentor for Inovativa Brasil, which is the largest startup acceleration program in Latin America.",
    description_pt:
      "Tenho mais de 17 anos atuando nas áreas de Varejo e Serviço. Participo da vertical de Varejo da Anjos do Brasil, onde atuo como mentor e também como investidor anjo. Além disso, sou mentor na Inovativa Brasil, que é o maior programa de aceleração de startups da América Latina.",
    languages_en: "pt - sp",
    languages_pt: "pt - es",
    languages_en_array: ["Portuguese", "Spanish"],
    languages_pt_array: ["Português", "Espanhol"],
    work_field_en: [
      "Retail",
      "Mentorship",
      "Investor",
      "E-commerce",
      "Strategic Planning",
    ],
    work_field_pt: [
      "Varejo",
      "Mentoria",
      "Investidor",
      "E-commerce",
      "Planejamento Estratégico",
    ],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/05_eduardo_balardim.jpg",
    flag: "brazil",
  },
  {
    id: 6,
    name: "Guilherme",
    last_name: "Yata",
    linkedin: "http://linkedin.com/in/guilhermeyata",
    description_en:
      "I have extensive experience in the retail, engineering, and international business sectors with almost 30 years in this field. I am a member of the administrative boards of some startups here in Brazil. Additionally, I am a managing partner at S3 projects, where we develop energy transition projects for companies.",
    description_pt:
      "Tenho muita experiência na área de varejo, engenharia e negócios internacionais com quase 30 anos nessa área. Faço parte do conselho administrativos de algumas startups aqui no Brasil. Além disso sou sócio-diretor da S3 projects onde desenvolvemos projetos transição energética para empresas.",
    languages_en: "en - pt - sp",
    languages_pt: "in - pt - es",
    languages_en_array: ["English", "Portuguese", "Spanish"],
    languages_pt_array: ["Inglês", "Português", "Espanhol"],
    work_field_en: [
      "Purchasing",
      "Business Model",
      "Product",
      "Operations",
      "Strategic Vision",
    ],
    work_field_pt: [
      "Compras",
      "Modelo de negócios",
      "Produto",
      "Operações",
      "Visão estratégica",
    ],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/06_guilherme_yata.jpeg",
    flag: "brazil",
  },
  {
    id: 7,
    name: "Simone",
    last_name: "Alves",
    linkedin:
      "https://www.linkedin.com/in/simonealvesrj?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    description_en:
      "As a consultant, I have experience in market research. With startups, I have been active since 2020 as a mentor and evaluator for various acceleration programs such as Inovativa Brasil, Inovativa de Impacto, Startup Conecta, Ela Empodera, Nexus Hub, CPS Inova, among others. I am also part of the Advisory Board of the startup Polimex Bioplásticos since 2021.",
    description_pt:
      "Como consultora tenho experiência em estudos de mercado. Com startups tenho atuado desde 2020 como mentora e avaliadora de diversos programas de aceleração como Inovativa Brasil, Inovativa de Impacto, Startup Conecta, Ela Empodera, Nexus Hub, CPS Inova, entre outros. Também sou do Conselho Consultivo ds startup Polimex Bioplásticos desde 2021",
    languages_en: "pt - en",
    languages_pt: "pt - in",
    languages_en_array: ["Portuguese", "English"],
    languages_pt_array: ["Português", "Inglês"],
    work_field_en: [
      "Public Funding",
      "Business Model",
      "Product",
      "Marketing",
      "B2B Sales",
    ],
    work_field_pt: [
      "Financiamento público",
      "Modelo de negócios",
      "Produto",
      "Marketing",
      "Vendas B2B",
    ],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/07_simone_alves.jpg",
    flag: "brazil",
  },
  {
    id: 8,
    name: "Rodrigo",
    last_name: "Grossi",
    linkedin: "https://www.linkedin.com/in/rodrigogrossi/",
    description_en:
      "I am Rodrigo, Founder of STARTUPS AI, partner and Chief Technology Officer at 2mi Group, Startup Manager in the International Startup Program at IFIA, Advisor to two Startups, and Official Mentor of Inovativa Brasil. I founded TeamHub and bring valuable experience from ideation to exit. I was CTO at SOLIDES, and I also have experience in renowned corporations such as TOTVS and FCA.",
    description_pt:
      "Eu sou Rodrigo, sou Founder da STARTUPS AI, sócio e Diretor Executivo de Tecnologia no grupo 2mi, Startup Manager no programa Internacional de Startups da IFIA, Advisor em duas Startups e Mentor Oficial do Inovativa Brasil. Fundei a TeamHub, e trago comigo a valiosa vivência desde a ideação até o exit. Fui CTO na SOLIDES, além de ter experiência em renomadas corporações como TOTVS e FCA.",
    languages_en: "pt - en",
    languages_pt: "pt - in",
    languages_en_array: ["Portuguese", "English"],
    languages_pt_array: ["Português", "Inglês"],
    work_field_en: [
      "Investors",
      "Business Model",
      "Leadership",
      "Pricing",
      "Valuation",
    ],
    work_field_pt: [
      "Investidores",
      "Modelo de negócios",
      "Liderança",
      "Precificação",
      "Valuation",
    ],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/08_rodrigo_grossi.jpeg",
    flag: "brazil",
  },
  {
    id: 9,
    name: "Marcos Tito",
    last_name: "Marques",
    linkedin: "https://www.linkedin.com/in/mrctito",
    description_en:
      "I am an Artificial Intelligence enthusiast with over 25 years of experience in the technology world, and my passion continues to grow. I am the kind of person who sees challenges as opportunities and learns by doing. My curiosity led me to develop an innovative AI product, and this self-instructive adventure has provided me with a wealth of practical knowledge in AI, as well as a profound understanding of its applications in the business world. Over the years, I have had the privilege of working with some of the largest software companies in the Brazilian and international markets, giving me a broad and diversified perspective of the industry. Leading multidisciplinary teams, including 100% remote teams, I have discovered the art of managing productivity and engagement from a distance. I firmly believe in the power of collaboration and communication to overcome obstacles and achieve ambitious goals. My experience spans various areas such as Education, Healthcare, Construction, HR, Hospitality, and more. I embrace both agile and traditional methodologies, and this flexibility allows me to adapt to different contexts and needs. In roles overseeing areas like Innovation, Support, Implementation, and Technology, I have developed a holistic vision that is crucial in software development.",
    description_pt:
      "Sou um entusiasta da Inteligência Artificial com mais de 25 anos de jornada no mundo da tecnologia, e minha paixão não para de crescer. Sou aquele tipo de pessoa que encara desafios como oportunidades e que aprende fazendo. Minha curiosidade me levou a desenvolver um produto de IA inovador, e essa aventura autoinstrutiva me trouxe um arsenal de conhecimentos práticos em IA, bem como uma compreensão profunda de suas aplicações no mundo dos negócios. Através dos anos, tive o privilégio de trabalhar com algumas das maiores empresas de software do mercado brasileiro e internacional, o que me proporcionou uma visão ampla e diversificada da indústria. Na liderança de equipes multidisciplinares, inclusive times 100% remotos, descobri a arte de gerenciar produtividade e engajamento à distância. Acredito firmemente no poder da colaboração e da comunicação para superar obstáculos e alcançar metas ambiciosas. Minha experiência se estende por áreas variadas como Educação, Saúde, Construção, RH, Hotelaria e muito mais. Sou adepto das metodologias ágeis e tradicionais, e essa flexibilidade me permite adaptar-me a diferentes contextos e necessidades. No comando de áreas como Inovação, Suporte, Implantação e Tecnologia, desenvolvi uma visão holística que é crucial no desenvolvimento de software.",
    languages_en: "pt",
    languages_pt: "pt",
    languages_en_array: ["Portuguese"],
    languages_pt_array: ["Português"],
    work_field_en: [
      "Partnerships",
      "Business Model",
      "Product",
      "Leadership",
      "B2B Sales",
      "Strategic Vision",
      "Company Direction",
    ],
    work_field_pt: [
      "Parcerias",
      "Modelo de negócios",
      "Produto",
      "Liderança",
      "Vendas B2B",
      "Visão estratégica",
      "Direcionamento da empresa",
    ],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/09_marcos_tito.jpeg",
    flag: "brazil",
  },
  {
    id: 10,
    name: "Andre",
    last_name: "Bretas",
    linkedin: "https://www.linkedin.com/in/andrebretas",
    description_en:
      "I work as a partner in startups and have previously served as CTO and COO in others I've been involved with. Additionally, I have experience in large corporations.",
    description_pt:
      "Atuo como sócio em startups e já atuei com CTO e COO em outras que passei. Além disso já tive experiência em grandes corporações.",
    languages_en: "pt - en",
    languages_pt: "pt - in",
    languages_en_array: ["Portuguese", "English"],
    languages_pt_array: ["Português", "Inglês"],
    work_field_en: [
      "Business Model",
      "Product",
      "E-commerce",
      "Leadership",
      "Digital Marketing",
    ],
    work_field_pt: [
      "Modelo de negócios",
      "Produto",
      "E-commerce",
      "Liderança",
      "Marketing digital",
    ],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/10_andre_bretas.jpeg",
    flag: "brazil",
  },
  {
    id: 11,
    name: "Praveen",
    last_name: "Desai",
    linkedin: "",
    description_en:
      "Engaged with startups since 2015, also fo ounded a company in 2017. Well connected with startup ecosystem in India.Established incubators in institutions of repute. Leveraging innovation and entrepreneurial ecosystem in the region.",
    description_pt:
      "Envolvido com startups desde 2015, também fundou uma empresa em 2017. Bem conectado com o ecossistema de startups na Índia. Estabeleceu incubadoras em instituições de renome. Alavancando a inovação e o ecossistema empreendedor na região.",
    languages_en: "en",
    languages_pt: "in",
    languages_en_array: ["English"],
    languages_pt_array: ["Inglês"],
    work_field_en: ["Business models"],
    work_field_pt: ["Modelo de negócios"],
    country_en: "India",
    country_pt: "Índia",
    photo: "/assets/experts/11_praveen_desai.png",
    flag: "india",
  },
  {
    id: 12,
    name: "Dr. Pranav Shimpi",
    last_name: "",
    linkedin: "",
    description_en:
      "I have been consulting organizations in health and productivity management for a decade, an insider to the startup scenario with experience to work on my own startup. I love coaching startup founders to find their purpose and start from there. I use my inquisitiveness to help shape up the journey and leverage my connection to foster quick focused growth.",
    description_pt:
      "Atuo como consultor de organizações na gestão da saúde e produtividade há uma década, um conhecedor do cenário de startups com experiência em trabalhar em minha própria startup. Adoro orientar fundadores de startups a encontrar seu propósito e começar por aí. Uso minha curiosidade para ajudar a moldar a jornada e alavancar minhas conexões para promover um crescimento rápido e focado.",
    languages_en: "en",
    languages_pt: "in",
    languages_en_array: ["English"],
    languages_pt_array: ["Inglês"],
    work_field_en: ["Risk management"],
    work_field_pt: ["Gestão de riscos"],
    country_en: "India",
    country_pt: "Índia",
    photo: "/assets/experts/12_pranav_shimpi.png",
    flag: "india",
  },
  {
    id: 13,
    name: "Dr. Shivaramakrishnan",
    last_name: "",
    linkedin: "",
    description_en: "Mentor",
    description_pt: "Mentor",
    languages_en: "en",
    languages_pt: "in",
    languages_en_array: ["English"],
    languages_pt_array: ["Inglês"],
    work_field_en: ["Private financing"],
    work_field_pt: ["Financiamento privado"],
    country_en: "India",
    country_pt: "Índia",
    photo: "/assets/experts/13_shivaramakrishnan.png",
    flag: "india",
  },
  {
    id: 14,
    name: "Wg Cdr Ragashree D Nair",
    last_name: "",
    linkedin: "",
    description_en: "Mentor & Strategic Advisor",
    description_pt: "Mentor e Consultor Estratégico",
    languages_en: "en",
    languages_pt: "in",
    languages_en_array: ["English"],
    languages_pt_array: ["Inglês"],
    work_field_en: ["Team Leadership"],
    work_field_pt: ["Liderança de equipe"],
    country_en: "India",
    country_pt: "Índia",
    photo: "/assets/experts/14_ragashree.png",
    flag: "india",
  },
  {
    id: 15,
    name: "G R Manjunath",
    last_name: "",
    linkedin: "",
    description_en:
      "Born into a business family of south india-based in bangalore-entrepreneurship is in the genes.",
    description_pt:
      "Nascido em uma família de negócios do sul da índia, baseado em bangalore, empreendedorismo está nos genes.",
    languages_en: "en",
    languages_pt: "in",
    languages_en_array: ["English"],
    languages_pt_array: ["Inglês"],
    work_field_en: ["Product-market fit"],
    work_field_pt: ["Adequação produto-mercado"],
    country_en: "India",
    country_pt: "Índia",
    photo: "/assets/experts/15_manjunath.png",
    flag: "india",
  },
  {
    id: 16,
    name: "Gedam",
    last_name: "Uday Kumar",
    linkedin: "",
    description_en:
      "Worked on real-time projects and participated in national-level competitions and hackathons",
    description_pt:
      "Trabalhei em projetos em tempo real e participei de competições e hackathons em nível nacional",
    languages_en: "en",
    languages_pt: "in",
    languages_en_array: ["English"],
    languages_pt_array: ["Inglês"],
    work_field_en: ["Product development"],
    work_field_pt: ["Desenvolvimento de produtos"],
    country_en: "India",
    country_pt: "Índia",
    photo: "/assets/experts/16_gedam.png",
    flag: "india",
  },
  {
    id: 17,
    name: "Shivam",
    last_name: "Gupta",
    linkedin: "",
    description_en: "",
    description_pt: "",
    languages_en: "en",
    languages_pt: "in",
    languages_en_array: ["English"],
    languages_pt_array: ["Inglês"],
    work_field_en: ["B2G Sales"],
    work_field_pt: ["Vendas B2G"],
    country_en: "India",
    country_pt: "Índia",
    photo: "/assets/experts/17_shivam.png",
    flag: "india",
  },
  {
    id: 18,
    name: "Karan Mehta",
    last_name: "",
    linkedin: "",
    description_en:
      "I have spent 3 years in manufacturing high precision, class 3 medical device as well as 2 years in New York working with Deloitte on Strategy and Operations for global Pharma and medtech clients...",
    description_pt:
      "Passei 3 anos na fabricação de dispositivos médicos de alta precisão, classe 3, e 2 anos em Nova York trabalhando com a Deloitte em Estratégia e Operações para clientes globais de farmácia e medtech...",
    languages_en: "en",
    languages_pt: "in",
    languages_en_array: ["English"],
    languages_pt_array: ["Inglês"],
    work_field_en: ["Product development"],
    work_field_pt: ["Desenvolvimento de produtos"],
    country_en: "India",
    country_pt: "Índia",
    photo: "/assets/experts/18_karan.png",
    flag: "india",
  },
  {
    id: 19,
    name: "Alem Moreira Martins Junior",
    last_name: "",
    linkedin: "https://www.linkedin.com/in/alemjunior",
    description_en:
      "Engagement in Technological and Cultural Transformation Projects in Large and Medium-sized companies across various industries: Pulp and Paper, Mining, Logistics, Energy, Sustainability, Technology. Currently involved in a project as the Leader of Organizational Change Management.",
    description_pt:
      "Atuação em Projetos de Transformação Tecnológica e Cultural em empresas de Grande e Médio porte em diversas linhas de negócios: Papel e Celulose, Mineração, Logística, Energia, Sustentabilidade, Tecnologia. Atualmente em um Projeto na Função de Líder de Gestão de Mudanças Organizacionais.",
    languages_en: "pt - en - sp",
    languages_pt: "pt - in - es",
    languages_en_array: ["Portuguese", "English", "Spanish"],
    languages_pt_array: ["Português", "Inglês", "Espanhol"],
    work_field_en: [
      "Networking",
      "Business Model",
      "Product",
      "Internationalization",
      "Leadership",
    ],
    work_field_pt: [
      "Rede de relacionamento",
      "Modelo de negócios",
      "Produto",
      "Internacionalização",
      "Liderança",
    ],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/19_alem_moreira.png",
    flag: "brazil",
  },
  {
    id: 20,
    name: "Marcelo",
    last_name: "Vivacqua",
    linkedin: "https://www.linkedin.com/in/marcelo-vivacqua-phd-b92b7620/",
    description_en:
      "I work as a business consultant for micro and small businesses for over 10 years as the CEO of my consulting company Conecta International Business Consultancy and as a mentor for programs such as Inovativa Brasil, Inovativa de Impacto, Sinergia Amazônia, and Founders Institute.",
    description_pt:
      "Atuo como consultor de negócios de micro e pequenas empresas há mais de 10 anos como CEO da minha empresa de consultoria Conecta International Business Consultancy e como Mentor de Programas como Inovativa Brasil, Inovativa de Impacto, Sinergia Amazônia e Founders Institute.",
    languages_en: "pt - en",
    languages_pt: "pt - in",
    languages_en_array: ["Portuguese", "English"],
    languages_pt_array: ["Português", "Inglês"],
    work_field_en: [
      "Private Financing",
      "Public Financing",
      "Networking",
      "Business Model",
      "Product",
    ],
    work_field_pt: [
      "Financiamento privado",
      "Financiamento público",
      "Rede de relacionamento",
      "Modelo de negócios",
      "Produto",
    ],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/20_marcelo_vivacqua.png",
    flag: "brazil",
  },
  {
    id: 21,
    name: "Mário Alex",
    last_name: "Santos",
    linkedin: "https://www.linkedin.com/in/marioalexsantos/",
    description_en:
      "More than 24 years of experience in the IT market, working in major software companies such as TOTVS, Softplan, and Betha Sistemas.",
    description_pt:
      "Mais de 24 anos de experiência no mercado de TI, atuando em grandes empresas de software como TOTVS, Softplan e Betha Sistemas.",
    languages_en: "pt",
    languages_pt: "pt",
    languages_en_array: ["Portuguese"],
    languages_pt_array: ["Português"],
    work_field_en: ["Team Leadership", "Operations", "B2B Sales"],
    work_field_pt: ["Liderança de equipes", "Operações", "Vendas B2B"],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/21_mario_alex.png",
    flag: "brazil",
  },
  {
    id: 22,
    name: "Leandro",
    last_name: "Figueiredo",
    linkedin: "https://www.linkedin.com/in/lefigueiredo/",
    description_en:
      "Associate Professor at Fundação Dom Cabral. Postdoctoral degree in Economic Development and Strategy.",
    description_pt:
      "Professor Associado da Fundação Dom Cabral. Pós Doutor em Desenvolvimento Econômico e Estratégia.",
    languages_en: "pt - en",
    languages_pt: "pt - in",
    languages_en_array: ["Portuguese", "English"],
    languages_pt_array: ["Português", "Inglês"],
    work_field_en: [
      "Private Financing",
      "Public Financing",
      "Networking",
      "Business Model",
      "Marketing",
    ],
    work_field_pt: [
      "Financiamento privado",
      "Financiamento público",
      "Rede de relacionamento",
      "Modelo de negócios",
      "Marketing",
    ],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/22_leandro_figueiredo.png",
    flag: "brazil",
  },
  {
    id: 23,
    name: "Dr.",
    last_name: "Viggardan",
    linkedin: "",
    description_en:
      "Mentor to 22 firm. Have my own start up India recognised company.",
    description_pt:
      "Mentor de 22 empresas. Tenho minha própria startup, reconhecida na Índia.",
    languages_en: "en",
    languages_pt: "in",
    languages_en_array: ["English"],
    languages_pt_array: ["Inglês"],
    work_field_en: ["Purchasing (Suppliers)"],
    work_field_pt: ["Compras (Fornecedores)"],
    country_en: "India",
    country_pt: "Índia",
    photo: "/assets/experts/23_viggardan.jpg",
    flag: "india",
  },
  {
    id: 24,
    name: "Boddupally",
    last_name: "Suhas",
    linkedin: "",
    description_en: "No description",
    description_pt: "Sem descrição",
    languages_en: "en",
    languages_pt: "in",
    languages_en_array: ["English"],
    languages_pt_array: ["Inglês"],
    work_field_en: ["Marketing"],
    work_field_pt: ["Marketing"],
    country_en: "India",
    country_pt: "Índia",
    photo: "/assets/experts/24_boddupally.jpg",
    flag: "india",
  },
  {
    id: 25,
    name: "Prudhvi",
    last_name: "Pakalapati",
    linkedin: "",
    description_en:
      "My role involves offering practical guidance in key areas like strategic planning, financial management, understanding market dynamics, and enhancing operational efficiency. I focus on helping you navigate the challenges of running a business, from managing funds and legalities to scaling up and networking. The goal is to partner with you, providing insights and advice tailored to your unique journey, ensuring your business thrives in a competitive environment.",
    description_pt:
      "Minha função envolve oferecer orientação prática em áreas-chave como planejamento estratégico, gestão financeira, compreensão da dinâmica de mercado e aprimoramento da eficiência operacional. Concentro-me em ajudar você a enfrentar os desafios de administrar um negócio, desde gerenciar fundos e questões legais até expandir e construir redes de contatos. O objetivo é ser seu parceiro, fornecendo insights e conselhos personalizados para a sua jornada única, garantindo que seu negócio prospere em um ambiente competitivo.",
    languages_en: "en",
    languages_pt: "in",
    languages_en_array: ["English"],
    languages_pt_array: ["Inglês"],
    work_field_en: ["Product development"],
    work_field_pt: ["Desenvolvimento de produtos"],
    country_en: "India",
    country_pt: "Índia",
    photo: "/assets/experts/25_prudhvi.png",
    flag: "india",
  },
  {
    id: 26,
    name: "Eduardo Cesar",
    last_name: "Dechechi",
    linkedin: "https://www.linkedin.com/in/dechechi/",
    description_en:
      "UniHub Coordinator (Innovation and Entrepreneurship Hub of Unioeste in Foz do Iguaçu).",
    description_pt:
      "Coordenador de UniHub (Hub de inovação e empreendedorismo da Unioeste em Foz do Iguaçu).",
    languages_en: "pt - en",
    languages_pt: "pt - in",
    languages_en_array: ["Portuguese", "English"],
    languages_pt_array: ["Português", "Inglês"],
    work_field_en: ["Governmental Relationship", "Strategic Vision"],
    work_field_pt: ["Relacionamento Governamental", "Visão estratégica"],
    country_en: "Brazil",
    country_pt: "Brasil",
    photo: "/assets/experts/26_eduardo_dechechi.png",
    flag: "brazil",
  },
];

export const teamList: TeamProps[] = [
  {
    id: 1,
    name: "Marcelo Vivacqua",
    linkedin: "https://www.linkedin.com/in/marcelo-vivacqua-phd-b92b7620/",
    position_pt: "CEO",
    position_en: "CEO",
    photo: "/assets/team/01_marcelo.jpeg",
  },
  {
    id: 2,
    name: "Rodrigo Grossi",
    linkedin: "https://www.linkedin.com/in/rodrigogrossi/",
    position_pt: "COO",
    position_en: "COO",
    photo: "/assets/team/02_rodrigo.jpeg",
  },
  {
    id: 3,
    name: "Andrio Corrêa",
    linkedin: "https://www.linkedin.com/in/andriocorrea/",
    position_pt: "CTO",
    position_en: "CTO",
    photo: "/assets/team/03_andrio.jpeg",
  },
  {
    id: 4,
    name: "Maria Goreti",
    linkedin: "https://www.linkedin.com/in/maria-goreti-freitas-phd-68a27738/",
    position_pt: "Advisor de Relações Internacionais",
    position_en: "International Relations Advisor",
    photo: "/assets/team/04_maria.jpeg",
  },
  {
    id: 5,
    name: "Mário Alex",
    linkedin: "https://www.linkedin.com/in/marioalexsantos/",
    position_pt: "Advisor de Gestão de Projetos e Experiência do Cliente",
    position_en: "Project Management and Customer Experience Advisor",
    photo: "/assets/team/05_mario.jpeg",
  },
  {
    id: 6,
    name: "Yadira Galeano",
    linkedin: "https://www.linkedin.com/in/yadirdiazgaleano/",
    position_pt: "Advisor de Gestão de Risco e Continuidade do Negócio",
    position_en: "Risk Management and Business Continuity Advisor",
    photo: "/assets/team/06_yadira.jpeg",
  },
  {
    id: 7,
    name: "Marcos Tito",
    linkedin: "https://www.linkedin.com/in/mrctito/",
    position_pt: "Advisor de IA",
    position_en: "AI Advisor",
    photo: "/assets/team/07_marcos.jpeg",
  },
  {
    id: 9,
    name: "Marco de Biasi",
    linkedin: "https://www.linkedin.com/in/debiasimarco/",
    position_pt: "Advisor de Investimentos",
    position_en: "Investment Advisor",
    photo: "/assets/team/09_marco.jpeg",
  },
  {
    id: 10,
    name: "Anand Kannan",
    linkedin: "https://www.linkedin.com/in/anand-kannan-24138b20a/",
    position_pt: "Head SGL India",
    position_en: "Head SGL India",
    photo: "/assets/team/10_anand.jpeg",
  },
];

export const bannersList: BannersProps = {
  investors_banner_en: "/assets/banners/investors_banner_en.png",
  investors_banner_pt: "/assets/banners/investors_banner_pt.png",
  main_banner_en: "/assets/banners/main_banner_en.png",
  main_banner_pt: "/assets/banners/main_banner_pt.png",
  main_banner_mobile_en: "/assets/banners/main_banner_mobile_en.png",
  main_banner_mobile_pt: "/assets/banners/main_banner_mobile_pt.png",
  mentors_banner_en: "/assets/banners/mentors_banner_en.png",
  mentors_banner_pt: "/assets/banners/mentors_banner_pt.png",
  startups_banner_en: "/assets/banners/startups_banner_en.png",
  startups_banner_pt: "/assets/banners/startups_banner_pt.png",
};
